import {useEffect,useState} from 'react';
import type {Habit} from '../../shared/models';
import type {CareConfig} from '../../shared/care';
import {localDay} from '../../shared/domain';
import {useDaily,useDailyAction,DailyDialog,DailyError} from './daily-context';
export function CareChecks({habitId,day=localDay()}:{habitId:number;day?:string}){const {data}=useDaily(),{run,error,busy}=useDailyAction(),slots=data.slots.filter(s=>s.active&&s.habit_id===habitId&&s.created_at.slice(0,10)<=day).sort((a,b)=>a.time.localeCompare(b.time));return <div className="care-checks">{slots.map(slot=>{const checked=data.checks.find(c=>c.slot_id===slot.id&&c.day===day);return <button type="button" className={`care-chip ${checked?.done===1?'done':checked?.done===0?'missed':''}`} key={slot.id} disabled={busy} aria-pressed={checked?.done===1} onClick={()=>void run(api=>api.careMark({slot_id:slot.id,day,done:checked?.done===1?null:true}))}><span>{checked?.done===1?'✓':'○'}</span><span>{slot.label}<small>{slot.time}</small></span></button>;})}<DailyError message={error}/></div>;}
type CareGroup='care'|'habit';
export function CareSettings({onEdit,onCreate,initialGroup='habit'}:{onEdit?:(habit:Habit)=>void;onCreate?:(group:CareGroup)=>void;initialGroup?:CareGroup}){
  const {data}=useDaily(),{run,error,busy}=useDailyAction(),[group,setGroup]=useState<CareGroup>(initialGroup),[edit,setEdit]=useState<Habit|null>(null);
  useEffect(()=>setGroup(initialGroup),[initialGroup]);
  const items=data.habits.filter(h=>h.active&&(data.preferences.find(p=>p.id===h.id)?.role??'habit')===group).sort((a,b)=>a.sort_order-b.sort_order);
  return <section className="daily-panel" aria-label="Уход и привычки"><div className="daily-heading care-heading"><div className="daily-tabs" role="group" aria-label="Раздел"><button type="button" aria-pressed={group==='care'} onClick={()=>setGroup('care')}>Уход</button><button type="button" aria-pressed={group==='habit'} onClick={()=>setGroup('habit')}>Привычки</button></div>{onCreate&&<button type="button" className="daily-button primary" onClick={()=>onCreate(group)}>+ Добавить</button>}</div>{items.map(h=>{
    const slots=data.slots.filter(s=>s.habit_id===h.id&&s.active),destination=group==='care'?'habit':'care',moveLabel=destination==='care'?'В уход':'В привычки';
    return <article className="daily-row care-setting-row" key={h.id}><div><strong>{h.name}</strong>{(slots.length>0||h.period==='weekly')&&<small>{slots.length?slots.map(s=>`${s.label} ${s.time}`).join(' · '):'Раз в неделю'}</small>}</div><div className="daily-actions">{h.kind==='positive'&&h.period==='daily'&&h.format==='boolean'&&<button type="button" className="daily-button subtle" aria-label={`Время: ${h.name}`} onClick={()=>setEdit(h)}>Время</button>}<button type="button" className="daily-button subtle care-move" disabled={busy} aria-label={`${moveLabel}: ${h.name}`} onClick={()=>void run(api=>api.careRole({habit_id:h.id,role:destination})).then(ok=>{if(ok)setGroup(destination);})}>{moveLabel} →</button>{onEdit&&<button type="button" className="daily-icon-button" title="Изменить" aria-label={`Изменить ${h.name}`} onClick={()=>onEdit(h)}>⋯</button>}</div></article>;
  })}{!items.length&&<p className="daily-empty">Пока пусто</p>}<DailyError message={error}/>{edit&&<CareEditor habit={edit} onClose={()=>setEdit(null)}/>}</section>;
}
function CareEditor({habit,onClose}:{habit:Habit;onClose:()=>void}){
  const {data,reminders}=useDaily(),{run,error,busy}=useDailyAction(),[slots,setSlots]=useState<CareConfig['slots']>(data.slots.filter(s=>s.habit_id===habit.id&&s.active).map(s=>({id:s.id,label:s.label,time:s.time,notify:Boolean(s.notify)}))),[permissionNote,setPermissionNote]=useState('');
  const patch=(index:number,values:Partial<CareConfig['slots'][number]>)=>setSlots(list=>list.map((s,i)=>i===index?{...s,...values}:s));
  return <DailyDialog title={habit.name} onClose={onClose}><form className="daily-form" onSubmit={e=>{e.preventDefault();let canClose=true;void run(async api=>{if(slots.some(s=>s.notify)&&reminders){const permission=await reminders.permission();if(!permission.enabled){canClose=false;setPermissionNote('Уведомления отключены в системе.');}}await api.careConfig({habit_id:habit.id,role:data.preferences.find(p=>p.id===habit.id)?.role??'habit',slots});}).then(ok=>{if(ok&&canClose)onClose();});}}><div className="daily-heading"><h3>Время</h3><button type="button" className="daily-button subtle" disabled={slots.length>=8} onClick={()=>setSlots(list=>[...list,{label:list.length===0?'Утро':list.length===1?'Вечер':`Отметка ${list.length+1}`,time:list.length?'20:00':'08:00',notify:false}])}>+ Добавить</button></div>{slots.map((slot,i)=><div className="care-slot-form" key={slot.id??i}><label><input aria-label={`Название отметки ${i+1}`} placeholder="Название" required maxLength={60} value={slot.label} onChange={e=>patch(i,{label:e.target.value})}/></label><label><input aria-label={`Время отметки ${i+1}`} required type="time" value={slot.time} onChange={e=>patch(i,{time:e.target.value})}/></label><label className="daily-checkbox"><input type="checkbox" checked={slot.notify} onChange={e=>patch(i,{notify:e.target.checked})}/>Напомнить</label><button type="button" className="daily-icon-button" aria-label={`Убрать ${slot.label}`} onClick={()=>setSlots(list=>list.filter((_,j)=>j!==i))}>×</button></div>)}<DailyError message={error}/>{permissionNote&&<p role="status">{permissionNote}</p>}<button className="daily-button primary" disabled={busy}>Сохранить</button></form></DailyDialog>;
}
