import {createContext,useCallback,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {dailyData,type DailyAPI,type DailyData} from '../../shared/daily';
import type {ReminderAPI} from '../../shared/reminders';
import './daily.css';
const empty=dailyData({format:'nexus-backup',version:11,exportedAt:'',tables:{}});
const Context=createContext<{api:DailyAPI|null;data:DailyData;reload:()=>Promise<void>;reminders?:ReminderAPI}>({api:null,data:empty,reload:async()=>{}});
export const useDaily=()=>useContext(Context);
export function DailyProvider({api,children,revision,reminders}:{api:DailyAPI;children:ReactNode;revision?:unknown;reminders?:ReminderAPI}){const [data,setData]=useState(empty);const reload=useCallback(async()=>{setData(await api.list());},[api]);useEffect(()=>{let live=true;const refresh=()=>void api.list().then(d=>{if(live)setData(d);}).catch(()=>{});refresh();window.addEventListener('focus',refresh);window.addEventListener('nexus:daily-change',refresh);const timer=setInterval(refresh,60_000);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('nexus:daily-change',refresh);};},[api,revision]);return <Context.Provider value={{api,data,reload,reminders}}>{children}</Context.Provider>;}
export function useDailyAction(){const {api,reload}=useDaily(),[error,setError]=useState(''),[busy,setBusy]=useState(false),locked=useRef(false);const run=async(fn:(api:DailyAPI)=>Promise<void>)=>{if(!api||locked.current)return false;locked.current=true;setBusy(true);try{await fn(api);await reload();window.dispatchEvent(new Event('nexus:daily-change'));setError('');return true;}catch(e){setError(e instanceof Error&&e.name==='ZodError'?'Проверь введённые данные.':e instanceof Error?e.message:'Не удалось сохранить.');return false;}finally{locked.current=false;setBusy(false);}};return {run,error,busy};}
export function DailyDialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return createPortal(<dialog ref={ref} className="daily-dialog" onCancel={e=>{e.preventDefault();onClose();}}><header><h2>{title}</h2><button type="button" className="daily-icon-button" aria-label="Закрыть" onClick={onClose}>×</button></header><div className="daily-dialog-body">{children}</div></dialog>,document.body);}
export function DailyError({message}:{message:string}){return message?<p className="daily-error" role="alert">{message}</p>:null;}
