import {useSystemCopy} from '../appearance';
import { createContext,useCallback,useContext,useEffect,useState,type ReactNode } from 'react';
import { growthData,metricValue,metricOptions,type GrowthAPI,type GrowthData,type Goal,type CustomMetric } from '../../shared/growth';
import { localDay,weekStart,money,toCents,displayDay } from '../../shared/domain';
import { GroupedNumberInput } from '../../shared/grouped-number';
import { askConfirm } from '../confirm';
import './growth.css';
const empty=growthData({format:'nexus-backup',version:9,exportedAt:'',tables:{}});
const Context=createContext<{api:GrowthAPI|null;data:GrowthData;reload:()=>Promise<void>}>({api:null,data:empty,reload:async()=>{}});
export function GrowthProvider({api,children,revision}:{api:GrowthAPI;children:ReactNode;revision?:unknown}){const [data,setData]=useState(empty);const reload=useCallback(async()=>setData(await api.list()),[api]);useEffect(()=>{let active=true;void api.list().then(value=>{if(active)setData(value);}).catch(()=>{});const focus=()=>void reload().catch(()=>{});window.addEventListener('focus',focus);const timer=setInterval(focus,60_000);return()=>{active=false;window.removeEventListener('focus',focus);clearInterval(timer);};},[api,reload,revision]);return <Context.Provider value={{api,data,reload}}>{children}</Context.Provider>;}
export const useGrowth=()=>useContext(Context);
function useAction(){const {api,reload}=useGrowth(),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function run(fn:(api:GrowthAPI)=>Promise<void>){if(!api)return;setBusy(true);try{await fn(api);await reload();setError('');}catch(e){setError(e instanceof Error&&e.name==='ZodError'?'Проверьте введённые данные.':e instanceof Error?e.message:'Не удалось сохранить.');}finally{setBusy(false);}}return {run,error,busy};}
export function WeeklyPlans(){
  const copy=useSystemCopy("growth-ui");

  const {data}=useGrowth(),{run,error,busy}=useAction();
  const [week,setWeek]=useState(weekStart(new Date(),1)),[title,setTitle]=useState(''),[recurring,setRecurring]=useState(false),[days,setDays]=useState<number[]>([0,2,4]),[editing,setEditing]=useState<string|null>(null);
  const plans=data.plans.filter(p=>p.week===week),date=new Date(`${week}T12:00:00`);
  const dates=Array.from({length:7},(_,i)=>{const d=new Date(date);d.setDate(d.getDate()+i);return localDay(d);});
  return <details className="growth-panel dominion-frame"><summary>{copy("Планы на неделю")}<small>{plans.length}</small></summary><div className="growth-body"><div className="growth-toolbar"><button className="button ghost small" onClick={()=>{const d=new Date(date);d.setDate(d.getDate()-7);setWeek(localDay(d));}}>←</button><strong>{displayDay(week)} — {displayDay(dates[6])}</strong><button className="button ghost small" onClick={()=>{const d=new Date(date);d.setDate(d.getDate()+7);setWeek(localDay(d));}}>→</button></div>
  {error&&<p className="error-banner">{error}</p>}{plans.map(plan=>{
    const links=(data.planTasks??[]).filter(l=>l.plan_id===plan.id),ids=new Set(links.length?links.map(l=>l.task_id):plan.task_id?[plan.task_id]:[]);
    const tasks=data.tasks.filter(t=>ids.has(String(t.id))).sort((a,b)=>String(a.due_day).localeCompare(String(b.due_day))),selected=tasks.map(t=>String(t.due_day)),done=tasks.filter(t=>t.status==='done').map(t=>String(t.id));
    const save=(scheduled_days=selected,status:'open'|'done'=plan.status,task_status?:{id:string;status:'open'|'done'})=>run(api=>api.plan({id:plan.id,title:plan.title,week,scheduled_days,task_status,status}));
    const editor=editing===plan.id||!tasks.length;
    return <article className="growth-multiplan" key={plan.id}><div className="growth-plan-heading">{!tasks.length&&<button className={`growth-check ${plan.status==='done'?'done':''}`} disabled={busy} aria-label={`Отметить: ${plan.title}`} onClick={()=>void save([],plan.status==='done'?'open':'done')}>{plan.status==='done'?'✓':'○'}</button>}<strong>{plan.title}</strong>{tasks.length>0&&<small>{done.length}/{tasks.length}</small>}<button className="button ghost small" aria-expanded={editor} onClick={()=>setEditing(editor?null:plan.id)}>Дни</button><button className="button ghost small" aria-label={`Удалить план: ${plan.title}`} disabled={busy} onClick={async()=>{if(await askConfirm('Удалить план и все его дела?'))void run(api=>api.removePlan(plan.id));}}>×</button></div>
      {tasks.length>0&&<div className="growth-plan-checks">{tasks.map(task=><button key={String(task.id)} className={`growth-day-check ${task.status==='done'?'done':''}`} aria-pressed={task.status==='done'} aria-label={`Отметить: ${plan.title}, ${displayDay(String(task.due_day))}`} disabled={busy} onClick={()=>void save(selected,plan.status,{id:String(task.id),status:task.status==='done'?'open':'done'})}><span>{task.status==='done'?'✓':'○'}</span>{new Date(`${task.due_day}T12:00:00`).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'numeric'})}</button>)}</div>}
      {editor&&<div className="growth-days growth-plan-picker">{dates.map((day,i)=><button key={day} type="button" className={selected.includes(day)?'selected':''} aria-pressed={selected.includes(day)} aria-label={`Запланировать ${plan.title}: ${displayDay(day)}`} disabled={busy} onClick={async()=>{if(selected.includes(day)&&tasks.some(t=>t.due_day===day&&t.status==='done')&&!await askConfirm('Убрать этот день и его выполненное дело из плана?'))return;setEditing(plan.id);void save(selected.includes(day)?selected.filter(d=>d!==day):[...selected,day]);}}>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][i]}<small>{new Date(`${day}T12:00:00`).getDate()}</small></button>)}</div>}
    </article>;
  })}
  <form className="growth-add" onSubmit={e=>{e.preventDefault();void run(async api=>{await api.plan({title,week,scheduled_days:[],status:'open'});setTitle('');});}}><input aria-label="Новый план" value={title} onChange={e=>setTitle(e.target.value)} placeholder={copy("Тренировка, уборка…")} maxLength={120} required/><button className="button secondary" disabled={busy||!title.trim()}>Добавить</button></form>
  <details className="growth-repeat"><summary>{copy("Повторяющиеся дела")}<small>{data.repeats.filter(x=>x.active).length}</small></summary>{data.repeats.filter(x=>x.active).map(rule=><div className="growth-row" key={rule.id}><span><strong>{rule.title}</strong><small>{(JSON.parse(rule.weekdays_json) as number[]).map(d=>['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][d]).join(', ')}</small></span><button className="button ghost small" disabled={busy} onClick={async()=>{if(await askConfirm('Остановить повторение? Будущие невыполненные дела этой серии будут убраны.'))void run(api=>api.repeat({id:rule.id,title:rule.title,weekdays:JSON.parse(rule.weekdays_json) as number[],start_day:rule.start_day,active:0}));}}>Остановить</button></div>)}<button className="button ghost small" onClick={()=>setRecurring(!recurring)}>{recurring?'Закрыть':'+ Повторение'}</button>{recurring&&<RepeatForm days={days} setDays={setDays} busy={busy} onSave={(title)=>run(async api=>{await api.repeat({title,weekdays:days,start_day:localDay(),active:1});setRecurring(false);})}/>}</details></div></details>;
}
function RepeatForm({days,setDays,busy,onSave}:{days:number[];setDays:(x:number[])=>void;busy:boolean;onSave:(title:string)=>Promise<void>}){
  const copy=useSystemCopy("growth-ui");
const [title,setTitle]=useState('');return <form className="growth-form" onSubmit={e=>{e.preventDefault();void onSave(title);}}><label>Дело<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder={copy("Например, тренировка")}/></label><div className="growth-days">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((label,i)=><button type="button" aria-pressed={days.includes(i)} className={days.includes(i)?'selected':''} key={label} onClick={()=>setDays(days.includes(i)?days.filter(d=>d!==i):[...days,i])}>{label}</button>)}</div><button className="button primary" disabled={busy||!title.trim()||!days.length}>Создать повторение</button></form>;}
export function GoalsPanel({currency='RUB'}:{currency?:string}){
  const copy=useSystemCopy("growth-ui");
const {data}=useGrowth(),{run,error,busy}=useAction();const [edit,setEdit]=useState<Goal|null|undefined>(undefined),[name,setName]=useState(''),[target,setTarget]=useState(''),[saved,setSaved]=useState(''),[deadline,setDeadline]=useState('');function open(goal:Goal|null){setEdit(goal);setName(goal?.name??'');setTarget(goal?String(goal.target_cents/100):'');setSaved(goal?String(goal.saved_cents/100):'0');setDeadline(goal?.deadline??'');}
  return <section className="growth-panel dominion-frame"><header className="growth-toolbar"><h2>{copy("Финансовые цели")}</h2><button className="button ghost small" onClick={()=>open(null)}>+ Цель</button></header>{error&&<p className="error-banner">{error}</p>}<div className="growth-goals dominion-frame">{data.goals.filter(g=>g.active).map(g=><button className="growth-goal" key={g.id} onClick={()=>open(g)}><span><strong>{g.name}</strong><small>{g.deadline?`До ${displayDay(g.deadline)}`:'Без срока'}</small></span><b>{Math.floor(g.saved_cents/g.target_cents*100)}%</b><progress value={Math.min(g.saved_cents,g.target_cents)} max={g.target_cents}/><small>{money(g.saved_cents,currency)} из {money(g.target_cents,currency)}</small></button>)}</div>{!data.goals.some(g=>g.active)&&edit===undefined&&<p className="muted">{copy("На что хочешь накопить?")}</p>}{edit!==undefined&&<form className="growth-form" onSubmit={e=>{e.preventDefault();void run(async api=>{await api.goal({id:edit?.id,name,target_cents:toCents(target),saved_cents:saved.trim()?Math.round(Number(saved.replace(',','.'))*100):0,deadline:deadline||null,active:1});setEdit(undefined);});}}><div className="growth-fields"><label>Название<input required value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><label>Нужно накопить<GroupedNumberInput value={target} onValueChange={setTarget} required/></label><label>Уже отложено<GroupedNumberInput value={saved} onValueChange={setSaved}/></label><label>Срок<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div><small className="muted">Учёт цели не меняет баланс счетов.</small><div className="growth-toolbar"><button className="button primary" disabled={busy}>Сохранить</button><button className="button ghost" type="button" onClick={()=>setEdit(undefined)}>Закрыть</button>{edit&&<button type="button" className="button ghost" disabled={busy} onClick={async()=>{if(await askConfirm('Убрать цель в архив?'))void run(async api=>{await api.goal({id:edit.id,name:edit.name,target_cents:edit.target_cents,saved_cents:edit.saved_cents,deadline:edit.deadline,active:0});setEdit(undefined);});}}>В архив</button>}</div></form>}<details><summary>Архив</summary>{data.goals.filter(g=>!g.active).map(g=><div className="growth-row" key={g.id}><span>{g.name}</span><button className="button ghost small" disabled={busy} onClick={()=>void run(api=>api.goal({id:g.id,name:g.name,target_cents:g.target_cents,saved_cents:g.saved_cents,deadline:g.deadline,active:1}))}>Вернуть</button></div>)}</details></section>;
}
export function MetricFields({day}:{day:string}){const {data}=useGrowth(),{run,error}=useAction();return <><div className="growth-fields">{data.metrics.filter(m=>m.active).map(m=>{const value=metricValue(data.entries.find(e=>e.metric_id===m.id&&e.day===day));return <label key={m.id}>{m.name}{m.unit&&` · ${m.unit}`}{m.kind==='number'?<input key={`${day}:${value}`} type="number" min="0" max="1000000000" step="any" defaultValue={typeof value==='number'?value:''} onBlur={e=>{const value=e.target.value===''?null:Number(e.target.value);void run(api=>api.entry({metric_id:m.id,day,value}));}}/>:<select value={value===null?'':String(value)} onChange={e=>{const value=e.target.value;void run(api=>api.entry({metric_id:m.id,day,value:value===''?null:m.kind==='boolean'?value==='true':value}));}}><option value="">Не отмечено</option>{(m.kind==='boolean'?['true','false']:metricOptions(m)).map(v=><option key={v} value={v}>{m.kind==='boolean'?(v==='true'?'Да':'Нет'):v}</option>)}</select>}</label>;})}</div>{error&&<p className="error-banner">{error}</p>}</>;}
export function MetricSettings(){
  const copy=useSystemCopy("growth-ui");
const {data}=useGrowth(),{run,error,busy}=useAction();const [edit,setEdit]=useState<CustomMetric|null|undefined>(undefined),[name,setName]=useState(''),[kind,setKind]=useState<CustomMetric['kind']>('number'),[unit,setUnit]=useState(''),[options,setOptions]=useState('');function open(m:CustomMetric|null){setEdit(m);setName(m?.name??'');setKind(m?.kind??'number');setUnit(m?.unit??'');setOptions(m?metricOptions(m).join(', '):'');}
return <section className="growth-panel dominion-frame"><header className="growth-toolbar"><h2>{copy("Свои показатели")}</h2><button className="button ghost small" onClick={()=>open(null)}>+ Показатель</button></header>{data.metrics.filter(m=>m.active).map(m=><div className="growth-row" key={m.id}><span>{m.name}{m.unit&&` · ${m.unit}`}</span><button className="button ghost small" onClick={()=>open(m)}>Изменить</button></div>)}{error&&<p className="error-banner">{error}</p>}{edit!==undefined&&<form className="growth-form" onSubmit={e=>{e.preventDefault();void run(async api=>{await api.metric({id:edit?.id,name,kind,unit:kind==='number'?unit:'',options:kind==='choice'?options.split(',').map(x=>x.trim()).filter(Boolean):[],active:1});setEdit(undefined);});}}><div className="growth-fields"><label>Название<input required value={name} maxLength={120} placeholder={copy("Кофе, чтение, время на игры…")} onChange={e=>setName(e.target.value)}/></label><label>Тип<select disabled={Boolean(edit&&data.entries.some(e=>e.metric_id===edit.id))} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="number">Количество</option><option value="boolean">Да / нет</option><option value="choice">Варианты</option></select></label>{kind==='number'&&<label>Единица<input value={unit} maxLength={20} placeholder="мин, чашек, шагов" onChange={e=>setUnit(e.target.value)}/></label>}{kind==='choice'&&<label>Варианты через запятую<input value={options} onChange={e=>setOptions(e.target.value)} placeholder="Мало, обычно, много"/></label>}</div><div className="growth-toolbar"><button className="button primary" disabled={busy}>Сохранить</button><button type="button" className="button ghost" onClick={()=>setEdit(undefined)}>Закрыть</button>{edit&&<button type="button" className="button ghost" onClick={async()=>{if(await askConfirm('Скрыть показатель? Записи сохранятся.'))void run(async api=>{await api.metric({id:edit.id,name:edit.name,kind:edit.kind,unit:edit.unit,options:metricOptions(edit),active:0});setEdit(undefined);});}}>Скрыть</button>}</div></form>}<details><summary>Скрытые</summary>{data.metrics.filter(m=>!m.active).map(m=><div className="growth-row" key={m.id}><span>{m.name}</span><button className="button ghost small" onClick={()=>void run(api=>api.metric({id:m.id,name:m.name,kind:m.kind,unit:m.unit,options:metricOptions(m),active:1}))}>Вернуть</button></div>)}</details></section>;
}
