import {useSystemCopy} from '../appearance';
import { useEffect,useState } from 'react';
import { localDay,money } from '../../shared/domain';
import type { Insights } from '../../shared/insights';
import { useGrowth } from './growth-ui';
function useInsights(start:string,end:string){const {api,data}=useGrowth(),[value,setValue]=useState<Insights|null>(null),[error,setError]=useState('');useEffect(()=>{let current=true;setValue(null);if(api)void api.insights(start,end).then(v=>{if(current){setValue(v);setError('');}}).catch(e=>{if(current)setError(e instanceof Error?e.message:'Не удалось собрать статистику.');});return()=>{current=false;};},[api,data,start,end]);return {value,error};}
const duration=(minutes:number)=>`${Math.floor(Math.round(minutes)/60)} ч ${Math.round(minutes)%60} мин`;
export function WeekComparison({start,end,currency='RUB'}:{start:string;end:string;currency?:string}){
  const copy=useSystemCopy("insights-ui");
const {value,error}=useInsights(start,end);if(error)return <p className="error-banner">{error}</p>;if(!value)return null;const {current:c,previous:p}=value;const change=(a:number,b:number,format:(n:number)=>string)=>`${a-b>0?'+':''}${format(a-b)}`;const sleepDelta=c.sleep!==null&&p.sleep!==null?Math.round(c.sleep-p.sleep):null;
  return <details className="growth-panel dominion-frame"><summary>{copy("Сравнить с прошлой неделей")}</summary><div className="growth-comparison"><article><span>Расходы</span><strong>{money(c.expense,currency)}</strong><small>{change(c.expense,p.expense,n=>money(n,currency))}</small></article><article><span>{copy("Выполненные дела")}</span><strong>{c.doneTasks}</strong><small>{change(c.doneTasks,p.doneTasks,String)}</small></article><article><span>Средний сон</span><strong>{c.sleep===null?'Нет записей':duration(c.sleep)}</strong><small>{sleepDelta===null?'Мало данных':`${sleepDelta>0?'+':''}${sleepDelta} мин`}</small></article><article><span>{copy("Успех привычек")}</span><strong>{c.habitRate===null?'Нет отметок':`${Math.round(c.habitRate*100)}%`}</strong><small>{c.habitRate!==null&&p.habitRate!==null?`${Math.round((c.habitRate-p.habitRate)*100)>0?'+':''}${Math.round((c.habitRate-p.habitRate)*100)} п. п.`:'Мало данных'} · по отмеченным дням</small></article>{c.metrics.map(m=>{const prior=p.metrics.find(x=>x.id===m.id);return <article key={m.id}><span>{m.name}</span><strong>{+m.average.toFixed(1)} {m.unit}</strong><small>{prior?`${m.average-prior.average>0?'+':''}${+(m.average-prior.average).toFixed(1)} ${m.unit}`:'Нет прошлых записей'} · {m.days} записей</small></article>;})}</div></details>;
}
export function PatternsPanel(){
  const copy=useSystemCopy("insights-ui");
const day=localDay(),{value,error}=useInsights(day,day);return <details className="growth-panel dominion-frame"><summary>{copy("Закономерности")}</summary>{error?<p className="error-banner">{error}</p>:value?.patterns.length?<div className="growth-insights">{value.patterns.map(item=><article key={item.id}><p>{item.text}</p><small>{item.sample} записей · {item.detail}</small></article>)}</div>:<p className="muted">Мало данных</p>}</details>;}
