import {useSystemCopy} from '../appearance';
import {useDaily} from './daily-context';
import {useGrowth} from './growth-ui';
import {metricOptions} from '../../shared/growth';
import { isPositiveJournalAmount } from '../../shared/journal-schema';
import { displayDay } from '../../shared/domain';
import type { JournalAnalysis } from '../../shared/models';
import { jobStatusLabels } from '../../shared/models';
import { lifeSchema,markerOptions,markerLabels,type LifeSuggestions,type Marker } from '../../shared/life';
import { wellbeingOptions,wellbeingLabel } from '../../shared/wellbeing';
type Choice={id:number;name:string;kind?:string;target?:number};
type Props={analysis:JournalAnalysis;accounts:Choice[];categories:Choice[];habits:Choice[];jobs:{id:number;title:string}[];selected:Set<string>;applied:Set<string>;onSelect:(key:string,checked:boolean)=>void;onChange:(analysis:JournalAnalysis)=>void;busy?:boolean;transactions?:{day:string;amount:number;type:string;accountId:number}[];day:string};
export function JournalReview({analysis,accounts,categories,habits,jobs,selected,applied,onSelect,onChange,busy=false,transactions=[],day}:Props){
  const copy=useSystemCopy('journal-review');
  const {data:growth}=useGrowth(),{data:daily}=useDaily();
  const h=analysis.health,life=analysis.life??lifeSchema.parse({});
  const already=(key:string)=>applied.has(key)||(applied.has('health.sleep')&&(key==='health.sleep_start'||key==='health.sleep_end'));
  const health=(patch:Partial<JournalAnalysis['health']>)=>onChange({...analysis,health:{...h,...patch}});
  const changeLife=(patch:Partial<LifeSuggestions>)=>onChange({...analysis,life:{...life,...patch}});
  const number=(value:string)=>value===''?null:Number(value);
  const card=(key:string,label:string,controls:React.ReactNode,warning?:string)=>{
    const saved=already(key),chosen=selected.has(key);
    return <div key={key} className={`review-item ${saved?'applied':''}`}><label className="review-pick"><input type="checkbox" disabled={saved||busy} checked={saved||chosen} onChange={e=>onSelect(key,e.target.checked)}/><span>{label}{saved&&<small>Сохранено</small>}</span></label>{chosen&&!saved&&<div className="review-controls">{controls}</div>}{warning&&<p className="review-warning">{warning}</p>}</div>;
  };
  const control=(label:string,element:React.ReactNode,full=false)=><label className={`review-control ${full?'full':''}`}><span>{label}</span>{element}</label>;
  const items:React.ReactNode[]=[];
  if(h.weightKg!==null)items.push(card('health.weight',`Вес: ${h.weightKg} кг`,control('Вес, кг',<input type="number" min="1" max="500" step="0.1" value={h.weightKg} onChange={e=>health({weightKg:number(e.target.value)})}/>)));
  for(const [key,field,label] of [['health.sleep_start','sleepStart','Лёг спать'],['health.sleep_end','sleepEnd','Проснулся']] as const)if(h[field])items.push(card(key,`${label}: ${h[field]}`,control(label,<input type="time" value={h[field]??''} onChange={e=>health({[field]:e.target.value||null})}/>)));
  for(const key of ['mood','energy'] as const)if(h[key]!==null)items.push(card(`health.${key}`,`${key==='mood'?'Настроение':'Энергия'}: ${wellbeingLabel(key,h[key]!)}`,control('Вариант',<select value={h[key]!} onChange={e=>health({[key]:Number(e.target.value)})}>{wellbeingOptions[key].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>)));
  if(h.nutrition)items.push(card('health.nutrition',`Питание: ${{good:'Хорошо',normal:'Обычно',poor:'Плохо'}[h.nutrition]}`,control('Питание',<select value={h.nutrition} onChange={e=>health({nutrition:e.target.value as typeof h.nutrition})}><option value="good">Хорошо</option><option value="normal">Обычно</option><option value="poor">Плохо</option></select>)));
  h.habits.forEach(item=>{const habit=habits.find(x=>x.id===item.habitId),avoid=habit?.kind==='avoid';items.push(card(`health.habit.${item.habitId}`,`${habit?.name??'Привычка'}: ${avoid?(item.value===0?'Не было':'Было'):(item.status==='done'?'Выполнено':'Не выполнено')}`,<>{control('Привычка',<select value={item.habitId} onChange={e=>{const id=Number(e.target.value),target=habits.find(x=>x.id===id);onSelect(`health.habit.${item.habitId}`,false);onSelect(`health.habit.${id}`,true);health({habits:h.habits.map(x=>x===item?{...x,habitId:id,value:target?.kind==='avoid'?(x.status==='done'?0:1):x.status==='done'?Math.max(1,target?.target??x.value):0}:x)});}}>{habits.filter(x=>!daily.slots.some(s=>s.active&&s.habit_id===x.id)&&(x.id===item.habitId||!h.habits.some(other=>other.habitId===x.id))).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>)}{control('Отметка',<select value={avoid?(item.value===0?'done':'missed'):item.status} onChange={e=>health({habits:h.habits.map(x=>x===item?{...x,status:e.target.value as 'done'|'missed',value:avoid?(e.target.value==='done'?0:1):e.target.value==='done'?Math.max(1,x.value):0}:x)})}><option value="done">{avoid?'Не было · успех':'Выполнено'}</option><option value="missed">{avoid?'Было · срыв':'Не выполнено'}</option></select>)}{!avoid&&control('Количество',<input type="number" min="0" step="0.1" value={item.value} onChange={e=>health({habits:h.habits.map(x=>x===item?{...x,value:Number(e.target.value)}:x)})}/>)}</>));});
  analysis.finance.forEach((item,i)=>{
    const update=(patch:Partial<typeof item>)=>onChange({...analysis,finance:analysis.finance.map((x,index)=>index===i?{...x,...patch}:x)});
    const complete=isPositiveJournalAmount(item.amountCents);
    const duplicate=complete&&transactions.some(x=>x.day===day&&x.amount===item.amountCents&&x.type===item.type&&x.accountId===item.accountId);
    items.push(card(`finance.${i}`,`${item.type==='expense'?'Расход':'Доход'}: ${complete?(item.amountCents!/100).toLocaleString('ru-RU'):(item.note?item.note+' · ':'')+'укажите сумму'} · ${accounts.find(x=>x.id===item.accountId)?.name??'Выберите счёт'}`,<>{control('Сумма',<input type="number" step="0.01" min="0.01" value={item.amountCents===null?'':item.amountCents/100} placeholder="Укажите сумму" onChange={e=>update({amountCents:e.target.value===''?null:Math.max(0,Math.round(Number(e.target.value)*100))})}/>)}{control('Тип',<select value={item.type} onChange={e=>update({type:e.target.value as typeof item.type,categoryId:null})}><option value="expense">Расход</option><option value="income">Доход</option></select>)}{control('Счёт',<select value={item.accountId??''} onChange={e=>update({accountId:number(e.target.value)})}><option value="">Выберите</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>)}{item.type==='expense'&&control('Категория',<select value={item.categoryId??''} onChange={e=>update({categoryId:number(e.target.value)})}><option value="">Выберите</option>{categories.filter(x=>x.kind==='expense').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>)}{control('Заметка',<input value={item.note} onChange={e=>update({note:e.target.value})}/>,true)}</>,!complete?'Укажите сумму.':duplicate?'Похожая операция уже есть за этот день. Проверьте, не повторяется ли она.':(!item.accountId||(item.type==='expense'&&!item.categoryId))?'Выберите предложение и укажите счёт и категорию.':undefined));
  });
  analysis.work.forEach((item,i)=>items.push(card(`work.${i}`,`${jobs.find(x=>x.id===item.jobId)?.title??'Вакансия'} → ${jobStatusLabels[item.status]}`,control('Статус',<select value={item.status} onChange={e=>onChange({...analysis,work:analysis.work.map((x,index)=>index===i?{...x,status:e.target.value as typeof x.status}:x)})}>{Object.entries(jobStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>))));
  if(life.contexts.length)items.push(card('life.contexts',`Контекст: ${life.contexts.join(', ')}`,control('Контексты через запятую',<input value={life.contexts.join(', ')} onChange={e=>changeLife({contexts:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/>,true)));
  if(life.achievement)items.push(card('life.achievement',`Результат: ${life.achievement}`,control('Результат дня',<textarea rows={2} value={life.achievement} onChange={e=>changeLife({achievement:e.target.value})}/>,true)));
  for(const key of Object.keys(markerOptions) as Marker[])if(life[key])items.push(card(`life.${key}`,`${markerLabels[key]}: ${markerOptions[key].find(([value])=>value===life[key])?.[1]}`,control(markerLabels[key],<select value={life[key]!} onChange={e=>changeLife({[key]:e.target.value})}>{markerOptions[key].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>)));
  life.care?.forEach((item,i)=>{const slot=daily.slots.find(s=>s.id===item.slotId);if(!slot)return;items.push(card(`life.care.${i}`,`${daily.habits.find(h=>h.id===slot.habit_id)?.name} · ${slot.label}: ${item.done?'Выполнено':'Не выполнено'}`,control('Отметка',<select value={String(item.done)} onChange={e=>changeLife({care:life.care?.map((x,index)=>index===i?{...x,done:e.target.value==='true'}:x)})}><option value="true">Выполнено</option><option value="false">Не выполнено</option></select>)));});
  life.metrics?.forEach((item,i)=>{const metric=growth.metrics.find(m=>m.id===item.metricId&&m.active);if(!metric)return;items.push(card(`life.metric.${i}`,`${metric.name}: ${typeof item.value==='boolean'?(item.value?'Да':'Нет'):item.value}${metric.unit?' '+metric.unit:''}`,control(metric.name,metric.kind==='number'?<input type="number" min="0" step="any" value={Number(item.value)} onChange={e=>changeLife({metrics:life.metrics?.map((x,index)=>index===i?{...x,value:Number(e.target.value)}:x)})}/>:<select value={String(item.value)} onChange={e=>changeLife({metrics:life.metrics?.map((x,index)=>index===i?{...x,value:metric.kind==='boolean'?e.target.value==='true':e.target.value}:x)})}>{(metric.kind==='boolean'?['true','false']:metricOptions(metric)).map(v=><option value={v} key={v}>{metric.kind==='boolean'?(v==='true'?'Да':'Нет'):v}</option>)}</select>)));});
  life.tasks.forEach((item,i)=>items.push(card(`life.task.${i}`,`На ${displayDay(item.dueDay)}: ${item.title}`,<>{control('Дело',<input value={item.title} onChange={e=>changeLife({tasks:life.tasks.map((x,index)=>index===i?{...x,title:e.target.value}:x)})}/>)}{control('Дата',<input type="date" value={item.dueDay} onChange={e=>changeLife({tasks:life.tasks.map((x,index)=>index===i?{...x,dueDay:e.target.value}:x)})}/>)}</>)));
  life.memories.forEach((item,i)=>items.push(card(`life.memory.${i}`,`Сохранить момент: ${item.text}`,control(copy('Воспоминание'),<textarea rows={3} value={item.text} onChange={e=>changeLife({memories:life.memories.map((x,index)=>index===i?{text:e.target.value}:x)})}/>,true))));
  return <div className="review-editor">{items.length?items:<p className="life-muted">Прямых отметок не найдено. Текст остался в дневнике.</p>}</div>;
}
