import { askConfirm } from '../confirm';
import { useRef,useState } from 'react';
import { contextsOf,contextOptions,markerOptions,markerLabels,reviewSchema,type DayLifeData,type DayTask,type DetailPatch,type Marker,type SavedReview } from '../../shared/life';

export function CoachCard({saved}:{saved:SavedReview|undefined}){
  if(!saved)return null;
  let raw:unknown;try{raw=JSON.parse(saved.content_json);}catch{return null;}
  const parsed=reviewSchema.safeParse(raw);if(!parsed.success)return null;
  const value=parsed.data;
  return <div className="coach-card"><div className="life-eyebrow">ЛИЧНЫЙ НАСТАВНИК · {new Date(saved.created_at).toLocaleDateString('ru-RU')}</div><h3>{value.headline}</h3><div className="coach-columns">{([['wins','Что получилось'],['problems','Где просел'],['actions','Следующие шаги']] as const).map(([key,label])=><div className={`coach-part ${key}`} key={key}><h4>{label}</h4>{value[key].length?<ul>{value[key].map((item,i)=><li key={i}>{item}</li>)}</ul>:<p className="life-muted">Нет подтверждённых записей.</p>}</div>)}</div><p className="coach-closing">{value.closing}</p></div>;
}
type Props={data:DayLifeData;day:string;onDay:(day:string)=>void;onPatch:(day:string,patch:DetailPatch)=>Promise<void>;onMarkers:(markers:Marker[])=>Promise<void>;onTask:(input:{id?:string;title?:string;day:string;due_day:string;status?:'open'|'done'})=>Promise<void>;onMemory:(input:{id?:string;day:string;text:string})=>Promise<void>;onRemove:(table:'day_tasks'|'day_memories',id:string)=>Promise<void>;onReview:(day:string)=>Promise<void>};
export function LifeBoard({data,day,onDay,onPatch,onMarkers,onTask,onMemory,onRemove,onReview}:Props){
  const [tab,setTab]=useState<'day'|'memories'>('day'),[options,setOptions]=useState(false),[task,setTask]=useState(''),[due,setDue]=useState(day),[memory,setMemory]=useState(''),[month,setMonth]=useState(day.slice(0,7)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const detail=data.details.find(x=>x.day===day),contexts=contextsOf(detail),tasks=data.tasks.filter(x=>x.status==='open').sort((a,b)=>a.due_day.localeCompare(b.due_day)),done=data.tasks.filter(x=>x.due_day===day&&x.status==='done');
  const taskInput=(item:DayTask)=>({id:item.id,title:item.title,day:item.day,due_day:item.due_day,status:item.status});
  const memories=[...data.memories].filter(x=>x.day.startsWith(month)).sort((a,b)=>b.day.localeCompare(a.day)||b.created_at.localeCompare(a.created_at));
  const pending=useRef<Promise<void>>(Promise.resolve());
  async function run(fn:()=>Promise<void>){const operation=pending.current.catch(()=>{}).then(fn);pending.current=operation;try{await operation;setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Не удалось сохранить.');}}

  async function review(){setBusy(true);try{await pending.current;await onReview(day);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Не удалось разобрать день.');}finally{setBusy(false);}}
  return <section className="life-board"><header className="life-header"><div><h2>Мой день</h2></div><div className="life-tabs"><button className={tab==='day'?'active':''} onClick={()=>setTab('day')}>День</button><button className={tab==='memories'?'active':''} onClick={()=>setTab('memories')}>Воспоминания <span>{data.memories.length}</span></button></div></header>
  {message&&<p className="life-error" role="alert">{message}</p>}
  {tab==='day'?<><div className="life-toolbar"><label>Дата<input type="date" value={day} onChange={e=>{if(e.target.value){onDay(e.target.value);setDue(e.target.value);}}}/></label><button className="life-secondary" onClick={()=>setOptions(!options)}>{options?'Закрыть':'Личные показатели'}</button><button disabled={busy} onClick={()=>void review()}>{busy?'Разбираю день…':'Разобрать день'}</button></div>
  {options&&<div className="life-options"><span>Что вам интересно отмечать</span>{(Object.keys(markerOptions) as Marker[]).map(key=><label key={key}><input type="checkbox" checked={data.markers.includes(key)} onChange={e=>{const checked=e.target.checked;void run(()=>onMarkers(checked?[...data.markers,key]:data.markers.filter(x=>x!==key)));}}/>{markerLabels[key]}</label>)}</div>}
  <div className="life-grid"><div className="life-section"><h3>Чем был наполнен день</h3><div className="life-tags">{[...new Set([...contextOptions,...contexts])].map(tag=><button key={tag} className={contexts.includes(tag)?'selected':''} onClick={()=>void run(()=>onPatch(day,{contexts:contexts.includes(tag)?contexts.filter(x=>x!==tag):[...contexts,tag]}))}>{tag}</button>)}</div><label className="life-custom-context">Свой контекст<input placeholder="Например: встреча с друзьями" maxLength={60} onKeyDown={e=>{if(e.key==='Enter'&&e.currentTarget.value.trim()){const value=e.currentTarget.value.trim();e.currentTarget.value='';void run(()=>onPatch(day,{contexts:[...new Set([...contexts,value])]}));}}}/><small className="life-muted">Enter — добавить</small></label><div className="life-markers">{data.markers.map(key=><label key={key}>{markerLabels[key]}<select value={detail?.[key]??''} onChange={e=>{const value=e.target.value||null;void run(()=>onPatch(day,{[key]:value}));}}><option value="">Не отмечать</option>{markerOptions[key].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}</div></div>
  <div className="life-section"><h3>Что удалось продвинуть</h3><label>Результат дня<textarea key={`${day}:${detail?.achievement??''}`} defaultValue={detail?.achievement??''} rows={3} maxLength={1000} placeholder="Один конкретный шаг, который вы сделали" onBlur={e=>{const value=e.target.value;if(value!==(detail?.achievement??''))void run(()=>onPatch(day,{achievement:value}));}}/></label><h3 className="life-next-heading">Момент, который хочется сохранить</h3><label>Воспоминание<textarea value={memory} onChange={e=>setMemory(e.target.value)} maxLength={2000} rows={2} placeholder="Встреча, смешной случай, понравившийся фильм…"/></label><button className="life-secondary" disabled={!memory.trim()} onClick={()=>void run(async()=>{await onMemory({day,text:memory});setMemory('');})}>Сохранить момент</button></div>
  <div className="life-section life-task-section"><div className="life-subhead"><h3>Главные дела</h3></div>{tasks.length?<div className="life-task-list">{tasks.map(item=><div key={item.id} className="life-task"><button className="life-check" aria-label={`Выполнить: ${item.title}`} onClick={()=>void run(()=>onTask({...taskInput(item),status:'done'}))}>✓</button><div><input aria-label="Название дела" key={`${item.id}:${item.title}`} defaultValue={item.title} maxLength={300} onBlur={e=>{const value=e.target.value.trim();if(value&&value!==item.title)void run(()=>onTask({...taskInput(item),title:value}));}}/><input aria-label="Дата дела" type="date" value={item.due_day} onChange={e=>{const value=e.target.value;if(value)void run(()=>onTask({...taskInput(item),due_day:value}));}}/></div><button className="life-icon" aria-label={`Удалить: ${item.title}`} onClick={async ()=>{if((await askConfirm('Удалить это дело?')))void run(()=>onRemove('day_tasks',item.id));}}>×</button></div>)}</div>:<p className="life-muted">Свободно. Можно выбрать следующий шаг.</p>}{done.length>0&&<details><summary>Сделано: {done.length}</summary>{done.map(item=><div className="life-done" key={item.id}><span>{item.title}</span><button className="life-secondary" onClick={()=>void run(()=>onTask({...taskInput(item),status:'open'}))}>Вернуть</button></div>)}</details>}<div className="life-add-task"><label>Следующий шаг<input value={task} maxLength={300} onChange={e=>setTask(e.target.value)} placeholder="Написать рекрутеру"/></label><label>На когда<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button disabled={!task.trim()||!due} onClick={()=>void run(async()=>{await onTask({title:task,day,due_day:due});setTask('');})}>Добавить</button></div></div></div>
  <CoachCard saved={data.reviews.find(x=>x.kind==='day'&&x.start===day&&x.end===day)}/></>:<><div className="life-toolbar"><label>Месяц<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><span className="life-muted">Выбранные моменты остаются после очистки текстов дневника.</span></div>{memories.length?<div className="memory-gallery">{memories.map(item=><article className="memory-card" key={item.id}><header><time>{new Date(`${item.day}T12:00:00`).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</time><button className="life-icon" aria-label="Удалить воспоминание" onClick={async ()=>{if((await askConfirm('Удалить воспоминание?')))void run(()=>onRemove('day_memories',item.id));}}>×</button></header><textarea aria-label="Текст воспоминания" rows={4} key={`${item.id}:${item.text}`} defaultValue={item.text} onBlur={e=>{const value=e.target.value.trim();if(value&&value!==item.text)void run(()=>onMemory({id:item.id,day:item.day,text:value}));}}/></article>)}</div>:<p className="life-empty">Пока нет сохранённых моментов за этот месяц.</p>}</>}
  </section>;
}
