import {useSystemCopy} from '../appearance';
import {useState} from 'react';
import {localDay} from '../../shared/domain';
import type {DailyData} from '../../shared/daily';
import {useDaily,useDailyAction,DailyDialog,DailyError} from './daily-context';
import {ReflectionForm} from './reflection-ui';
export function routineSteps(data:DailyData,id:'morning'|'evening'){const candidates=[{id:'wake',label:'Время подъёма'},{id:'weight',label:'Вес'},...data.slots.filter(s=>s.active&&data.habits.some(h=>h.id===s.habit_id&&h.active)).sort((a,b)=>a.time.localeCompare(b.time)).map(s=>({id:`slot:${s.id}`,label:`${data.habits.find(h=>h.id===s.habit_id)?.name} · ${s.label}`})),...data.habits.filter(h=>h.active&&h.period==='daily'&&h.kind==='positive'&&h.format==='boolean'&&!data.slots.some(s=>s.habit_id===h.id&&s.active)).map(h=>({id:`habit:${h.id}`,label:h.name})),{id:'reflection',label:'Вопрос вечера'},{id:'journal',label:'Запись дня'}];const saved=data.routines.find(r=>r.id===id);let selected:string[];try{selected=saved?JSON.parse(saved.steps_json) as string[]:[];}catch{selected=[];}if(!saved)selected=id==='morning'?['wake','weight',...data.slots.filter(s=>s.active&&s.time<'14:00').map(s=>`slot:${s.id}`)]:[...data.slots.filter(s=>s.active&&s.time>='14:00').map(s=>`slot:${s.id}`),'reflection','journal'];return {candidates,selected,steps:selected.flatMap(key=>candidates.find(c=>c.id===key)?[candidates.find(c=>c.id===key)!]:[])};}
export function routineDone(data:DailyData,id:string,day=localDay()){if(id==='weight')return data.weights.some(w=>w.day===day);if(id==='wake')return data.health.some(h=>h.day===day&&h.sleep_end);if(id==='reflection')return data.answers.some(a=>a.day===day);if(id==='journal')return data.journalDays.includes(day);if(id.startsWith('slot:'))return data.checks.some(c=>c.slot_id===id.slice(5)&&c.day===day&&c.done===1);const habit=data.habits.find(h=>h.id===Number(id.slice(6))),log=data.logs.find(l=>l.habit_id===habit?.id&&l.day===day);return Boolean(habit&&log?.status==='done'&&log.value>=habit.target);}
export function RoutineButton({id,onOpen}:{id:'morning'|'evening';onOpen:()=>void}){
  const copy=useSystemCopy("routine-ui");
const {data}=useDaily(),{steps}=routineSteps(data,id),done=steps.filter(s=>routineDone(data,s.id)).length;return <button className={`daily-launch ${steps.length&&done===steps.length?'complete':''}`} onClick={onOpen}><span className="daily-launch-icon">{id==='morning'?'☀':'◒'}</span><span><strong>{id==='morning'?copy("Утро"):copy("Вечер")}</strong><small>{steps.length?`${done}/${steps.length}`:'Настроить'}</small></span><span aria-hidden="true">›</span></button>;}
export function RoutineDialog({id,onClose,onJournal}:{id:'morning'|'evening';onClose:()=>void;onJournal:()=>void}){
  const copy=useSystemCopy("routine-ui");
const {data}=useDaily(),{run,error,busy}=useDailyAction(),{steps,candidates,selected}=routineSteps(data,id),[index,setIndex]=useState(()=>(()=>{const first=steps.findIndex(s=>!routineDone(data,s.id));return first<0?steps.length:first;})()),[edit,setEdit]=useState(false),[selection,setSelection]=useState(selected);const step=steps[index],done=steps.filter(s=>routineDone(data,s.id)).length;const next=()=>setIndex(i=>Math.min(i+1,steps.length));return <DailyDialog title={id==='morning'?copy("Утро"):copy("Вечер")} onClose={onClose}><div className="routine-progress"><span>{done}/{steps.length}</span><progress max={Math.max(1,steps.length)} value={done}/><button className="daily-button subtle" onClick={()=>setEdit(!edit)}>{edit?'Закрыть':'Настроить'}</button></div>{edit?<form className="daily-form" onSubmit={e=>{e.preventDefault();void run(api=>api.routine({id,steps:selection})).then(ok=>{if(ok){setEdit(false);setIndex(0);}});}}>{candidates.map(c=><label className="daily-checkbox" key={c.id}><input type="checkbox" checked={selection.includes(c.id)} onChange={e=>setSelection(old=>e.target.checked?[...old,c.id]:old.filter(x=>x!==c.id))}/>{c.id==='reflection'?copy('Вопрос вечера'):c.label}</label>)}<button className="daily-button primary" disabled={busy}>Сохранить состав</button></form>:step?<><div className="routine-step-label">ШАГ {index+1} / {steps.length}</div><h3 className="routine-step-title">{step.id==='reflection'?copy('Вопрос вечера'):step.label}</h3><RoutineStep key={step.id} id={step.id} next={next} onJournal={()=>{onClose();onJournal();}}/>{routineDone(data,step.id)&&<p className="daily-caption good">✓ Уже отмечено</p>}<div className="routine-navigation"><button className="daily-button subtle" disabled={!index} onClick={()=>setIndex(i=>i-1)}>Назад</button><button className="daily-button subtle" onClick={next}>Дальше →</button></div></>:<div className="routine-finish"><span>✓</span><h3>{steps.length&&done===steps.length?'Всё отмечено':'На этом всё'}</h3><p>{done}/{steps.length} выполнено</p><button className="daily-button primary" onClick={onClose}>Готово</button></div>}<DailyError message={error}/></DailyDialog>;}
function RoutineStep({id,next,onJournal}:{id:string;next:()=>void;onJournal:()=>void}){
  const copy=useSystemCopy("routine-ui");
const {data}=useDaily(),{run,error,busy}=useDailyAction(),day=localDay(),[value,setValue]=useState(id==='weight'?String(data.weights.find(w=>w.day===day)?.weight_kg??''):data.health.find(h=>h.day===day)?.sleep_end??'');if(id==='reflection')return <ReflectionForm onSaved={next}/>;if(id==='journal')return <button className="daily-button primary" onClick={onJournal}>{copy("Рассказать о дне →")}</button>;return <><form className="daily-form" onSubmit={e=>{e.preventDefault();void run(api=>id.startsWith('slot:')?api.careMark({slot_id:id.slice(5),day,done:true}):id.startsWith('habit:')?api.routineEntry({kind:'habit',habit_id:Number(id.slice(6)),day,done:true}):api.routineEntry(id==='weight'?{kind:'weight',day,value:Number(value.replace(',','.'))}:{kind:'wake',day,value})).then(ok=>{if(ok)next();});}}>{(id==='weight'||id==='wake')&&<label>{id==='weight'?'Вес, кг':'Проснулся'}<input autoFocus required type={id==='weight'?'number':'time'} min={id==='weight'?1:undefined} max={id==='weight'?500:undefined} step={id==='weight'?'0.1':undefined} value={value} onChange={e=>setValue(e.target.value)}/></label>}<button className="daily-button primary" disabled={busy}>{id==='weight'||id==='wake'?'Записать':'Сделано'}</button></form><DailyError message={error}/></>;}
