"""Invitation-only accounts. Credentials and accounting never come from sync snapshots."""
import base64
import hashlib
import hmac
import json
import os
import secrets
import tempfile
import threading
import uuid
from pathlib import Path


class AccountError(Exception):
    def __init__(self, status, code):
        self.status, self.code = status, code
        super().__init__(code)


def write_private(path: Path, value: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
        temporary = Path(stream.name)
        os.chmod(temporary, 0o600)
        stream.write(json.dumps(value, ensure_ascii=False, separators=(',', ':')).encode())
        stream.flush()
        os.fsync(stream.fileno())
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


class Signal:
    def __init__(self):
        self.lock = threading.RLock()
        self.changed = threading.Condition(self.lock)
        self.events = threading.BoundedSemaphore(4)
        self.revision = None


class Accounts:
    def __init__(self, root: Path):
        self.root = root
        self.lock = threading.RLock()
        self.signals = {}

    def registry(self):
        path = self.root / 'accounts.json'
        return json.loads(path.read_text('utf-8')) if path.exists() else {'version': 1, 'users': []}

    def authenticate(self, supplied, owner_token):
        if owner_token and hmac.compare_digest(supplied, owner_token):
            return {'id': 'owner', 'name': 'Личный', 'role': 'owner', 'active': True}
        digest = hashlib.sha256(supplied.encode()).hexdigest()
        with self.lock:
            for user in self.registry()['users']:
                if user['active'] and (hmac.compare_digest(digest, user['token_hash']) or hmac.compare_digest(digest, user.get('invite_hash', ''))):
                    return dict(user, role='guest')
        return None

    def invitation(self, identity):
        """Owner-only API calls this. Preserve codes so already connected devices stay connected."""
        with self.lock:
            registry = self.registry()
            user = next((u for u in registry['users'] if u['id'] == identity), None)
            if user is None:
                raise AccountError(404, 'user_not_found')
            path = self.directory(user) / 'invitation.json'
            if path.is_file():
                code = json.loads(path.read_text('utf-8'))['code']
            else:
                raw = base64.b32encode(secrets.token_bytes(15)).decode('ascii')
                code = 'NEXUS-' + '-'.join(raw[i:i+4] for i in range(0, 24, 4))
                write_private(path, {'code': code})
            digest = hashlib.sha256(code.encode()).hexdigest()
            if user.get('invite_hash') != digest:
                user['invite_hash'] = digest
                write_private(self.root / 'accounts.json', registry)
            return dict(user, role='guest'), code

    def directory(self, user):
        if user['id'] == 'owner':
            return self.root
        # Registry ids are generated by the server, not taken from a client header/path.
        identity = str(uuid.UUID(user['id']))
        return self.root / 'users' / identity

    def signal(self, user):
        with self.lock:
            if user['id'] not in self.signals:
                self.signals[user['id']] = Signal()
            return self.signals[user['id']]

    def public(self, user):
        result = {key: user[key] for key in ('id', 'name', 'role', 'active')}
        if user['id'] != 'owner':
            result.update(monthlyLimitCents=user['monthly_limit_cents'], models=user['models'], aiMode='device' if user.get('ai_key_hash') else 'unconfigured')
            if user.get('ai_key_hash'):
                result['aiKeyHash'] = user['ai_key_hash']
        return result

    def create(self, name, limit, models, ai_credentials=None):
        if not isinstance(name, str) or not 1 <= len(name.strip()) <= 80 or type(limit) is not int or not 0 <= limit <= 10000:
            raise AccountError(400, 'invalid_user')
        if not isinstance(models, dict) or set(models) != {'cheapModel', 'standardModel', 'advancedModel', 'transcriptionModel'} or any(not isinstance(v, str) or len(v) > 200 for v in models.values()):
            raise AccountError(400, 'invalid_models')
        if ai_credentials is not None:
            import re
            if not isinstance(ai_credentials, dict) or set(ai_credentials) != {'key','hash','monthlyLimitCents'} or ai_credentials['monthlyLimitCents'] != limit or not isinstance(ai_credentials['hash'],str) or not re.fullmatch(r'[a-f0-9]{64}',ai_credentials['hash']) or not isinstance(ai_credentials['key'],str) or not re.fullmatch(r'sk-or-v1-[a-zA-Z0-9_-]{20,480}',ai_credentials['key']):
                raise AccountError(400, 'invalid_user_ai_key')
        with self.lock:
            registry = self.registry()
            if len(registry['users']) >= 20:
                raise AccountError(409, 'user_limit')
            token = secrets.token_urlsafe(48)
            user = {'id': str(uuid.uuid4()), 'name': name.strip(), 'active': True, 'monthly_limit_cents': limit, 'models': models, 'token_hash': hashlib.sha256(token.encode()).hexdigest()}
            directory = self.directory(user)
            directory.mkdir(parents=True, mode=0o700, exist_ok=False)
            os.chmod(directory, 0o700)
            if ai_credentials:
                user['ai_key_hash'] = ai_credentials['hash']
                write_private(directory / 'ai-device-key.json', {'key':ai_credentials['key']})
            registry['users'].append(user)
            write_private(self.root / 'accounts.json', registry)
            return dict(user, role='guest'), token

    def device_key(self, user):
        path = self.directory(user) / 'ai-device-key.json'
        if not path.is_file():
            raise AccountError(409, 'ai_key_missing')
        return json.loads(path.read_text('utf-8'))['key']

    def update(self, identity, changes):
        if not isinstance(changes, dict) or not set(changes) <= {'active', 'monthlyLimitCents'}:
            raise AccountError(400, 'invalid_user_change')
        if 'active' in changes and type(changes['active']) is not bool:
            raise AccountError(400, 'invalid_user_change')
        if 'monthlyLimitCents' in changes and (type(changes['monthlyLimitCents']) is not int or not 0 <= changes['monthlyLimitCents'] <= 10000):
            raise AccountError(400, 'invalid_user_change')
        with self.lock:
            registry = self.registry()
            user = next((u for u in registry['users'] if u['id'] == identity), None)
            if not user:
                raise AccountError(404, 'user_not_found')
            if 'active' in changes:
                user['active'] = changes['active']
            if 'monthlyLimitCents' in changes:
                user['monthly_limit_cents'] = changes['monthlyLimitCents']
            write_private(self.root / 'accounts.json', registry)
            updated = dict(user, role='guest')
        with self.signal(user).changed:
            self.signal(user).changed.notify_all()
        return updated

    def active(self, user):
        if user['id'] == 'owner':
            return True
        with self.lock:
            return any(u['id'] == user['id'] and u['active'] for u in self.registry()['users'])



_stores = {}
_store_lock = threading.Lock()
def accounts(root):
    with _store_lock:
        key = str(root.resolve())
        if key not in _stores:
            _stores[key] = Accounts(root)
        return _stores[key]
