import { contextBridge, ipcRenderer } from 'electron';
import type { NexusAPI } from '../shared/models';

const call=async(channel:string,payload?:unknown)=>{const result=await ipcRenderer.invoke(channel,payload);if(/^(health:(saveHabit|moveHabit|saveDay|saveDayField|saveHabitLog|archiveHabit)|finance:(saveAccount|saveCategory|deleteCategory|saveTransaction|deleteTransaction)|journal:(save|update|apply)|life:(task|remove))$/.test(channel))window.dispatchEvent(new Event('nexus:daily-change'));return result;};
const api: NexusAPI = {
  daily:{list:()=>call('daily:list'),careConfig:x=>call('daily:careConfig',x),careMark:x=>call('daily:careMark',x),routine:x=>call('daily:routine',x),routineEntry:x=>call('daily:routineEntry',x),payment:x=>call('daily:payment',x),paymentAction:x=>call('daily:paymentAction',x),experiment:x=>call('daily:experiment',x),experimentMark:x=>call('daily:experimentMark',x),focus:x=>call('daily:focus',x),reflection:x=>call('daily:reflection',x)},
  growth:{insights:(start,end)=>call('growth:insights',{start,end}),list:()=>call('growth:list'),goal:input=>call('growth:goal',input),plan:input=>call('growth:plan',input),repeat:input=>call('growth:repeat',input),metric:input=>call('growth:metric',input),entry:input=>call('growth:entry',input),removePlan:id=>call('growth:removePlan',id)},
  reminders:{get:()=>call('reminders:get'),save:input=>call('reminders:save',input),permission:()=>call('reminders:permission')},
  updates:{status:()=>call('updates:status'),check:()=>call('updates:check'),download:()=>call('updates:download'),install:()=>call('updates:install')},
  profiles:{list:()=>call('profiles:list'),create:name=>call('profiles:create',name),select:id=>call('profiles:select',id)},
  accounts:{profile:()=>call('accounts:profile'),managementStatus:()=>call('accounts:managementStatus'),setManagementKey:key=>call('accounts:setManagementKey',key),list:()=>call('accounts:list'),invitation:id=>call('accounts:invitation',id),create:input=>call('accounts:create',input),update:input=>call('accounts:update',input)},
  life:{list:()=>call('life:list'),patch:input=>call('life:patch',input),markers:fields=>call('life:markers',fields),task:input=>call('life:task',input),memory:input=>call('life:memory',input),remove:input=>call('life:remove',input),review:input=>call('life:review',input)},
  investments:{list:()=>call('investments:list'),saveAccount:input=>call('investments:saveAccount',input),saveEntry:input=>call('investments:saveEntry',input),deleteEntry:id=>call('investments:deleteEntry',id)},
  health:{list:()=>call('health:list'),saveHabit:input=>call('health:saveHabit',input),moveHabit:input=>call('health:moveHabit',input),saveDay:input=>call('health:saveDay',input),saveDayField:input=>call('health:saveDayField',input),saveHabitLog:input=>call('health:saveHabitLog',input),archiveHabit:id=>call('health:archiveHabit',id)},
  finance:{list:()=>call('finance:list'),saveAccount:input=>call('finance:saveAccount',input),saveCategory:input=>call('finance:saveCategory',input),deleteCategory:id=>call('finance:deleteCategory',id),saveTransaction:input=>call('finance:saveTransaction',input),deleteTransaction:id=>call('finance:deleteTransaction',id),setBudget:input=>call('finance:setBudget',input)},
  work:{list:()=>call('work:list'),saveJob:input=>call('work:saveJob',input),changeStatus:input=>call('work:changeStatus',input),saveEntry:input=>call('work:saveEntry',input),saveCase:input=>call('work:saveCase',input),linkCase:input=>call('work:linkCase',input)},
  settings:{get:()=>call('settings:get'),save:input=>call('settings:save',input),setApiKey:key=>call('settings:setApiKey',key),testConnection:()=>call('settings:testConnection'),usage:()=>call('settings:usage')},
  ai:{run:input=>call('ai:run',input),parseVacancy:input=>call('ai:parseVacancy',input)},data:{export:()=>call('data:export'),import:()=>call('data:import'),remoteConfig:()=>call('data:remoteConfig'),setBackupPassphrase:passphrase=>call('data:setBackupPassphrase',passphrase),copyRemoteToken:()=>call('data:copyRemoteToken'),enableAndroidAI:()=>call('data:enableAndroidAI'),configureRemote:input=>call('data:configureRemote',input),remoteList:()=>call('data:remoteList'),remoteUpload:()=>call('data:remoteUpload'),remoteRestore:id=>call('data:remoteRestore',id)},dashboard:{get:()=>call('dashboard:get'),weekly:period=>call('dashboard:weekly',period)},external:{open:url=>call('external:open',url)},journal:{editAnalysis:input=>call('journal:editAnalysis',input),list:()=>call('journal:list'),save:input=>call('journal:save',input),update:input=>call('journal:update',input),analyze:(id,overrideBudget)=>call('journal:analyze',{id,overrideBudget}),apply:input=>call('journal:apply',input),transcribe:input=>call('journal:transcribe',input)}
};
contextBridge.exposeInMainWorld('nexus',api);
