import {afterEach,describe,it,expect} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {chartGeometry} from '../shared/chart-geometry';
import {DateChart} from './date-chart';
import {setTheme} from './appearance';
afterEach(()=>{cleanup();setTheme('standard');});
describe('actual dated charts',()=>{
 it('uses the same currency units on the scale and in the inspector',()=>{const {container}=render(<DateChart points={[{day:'2026-10-01',value:10000},{day:'2026-10-02',value:20000}]} formatValue={cents=>`${cents/100} ₽`}/>);expect(container.querySelector('.chart-axis')?.textContent).toContain('₽');expect(container.querySelector('.chart-inspection strong')?.textContent).toBe('200 ₽');expect(container.querySelector('.chart-axis')?.textContent).not.toContain('10000');});
 it('keeps the value scale readable across fractional and signed ranges',()=>{for(const values of [[78.2,78.9],[.01,.06],[-23,31],[9000,150000],[0,0]]){const g=chartGeometry(values.map((value,i)=>({day:`2026-10-0${i+1}`,value})),320,242,'bar')!;expect(g.ticks.length).toBeGreaterThanOrEqual(3);expect(g.ticks.length).toBeLessThanOrEqual(5);}});
 it('uses zero baseline for positive, negative and genuine zero bars',()=>{const g=chartGeometry([{day:'2026-10-01',value:20},{day:'2026-10-02',value:-10},{day:'2026-10-03',value:0}],600,274,'bar')!;expect(g.positions[0].y!).toBeLessThan(g.baseline);expect(g.positions[1].y!).toBeGreaterThan(g.baseline);expect(g.positions[2].y).toBe(g.baseline);setTheme('dominion');const {container}=render(<DateChart kind="bar" points={[{day:'2026-10-01',value:20},{day:'2026-10-02',value:-10},{day:'2026-10-03',value:0}]}/>);expect(container.querySelector('rect[data-value="0"]')?.getAttribute('height')).toBe('0');});
 it('handles missing, single and constant observations without a fake line',()=>{render(<DateChart points={[]}/>);expect(screen.getByText('Нет данных')).toBeTruthy();cleanup();const {container}=render(<DateChart points={[{day:'2026-10-04',value:78.2}]}/>);expect(container.querySelector('polyline')).toBeNull();expect(screen.getByText('78.2')).toBeTruthy();expect(screen.queryByRole('slider')).toBeNull();const g=chartGeometry([{day:'2026-10-01',value:78},{day:'2026-10-02',value:78}],600,274,'line')!;expect(g.max).toBeGreaterThan(g.min);});
 it('preserves temporal gaps and selects only actual values with keyboard controls',()=>{setTheme('dominion');const points=[{day:'2026-10-01',value:1},{day:'2026-10-02',value:null},{day:'2026-10-04',value:3}];const g=chartGeometry(points,600,274,'line')!;expect(g.positions[1].x-g.positions[0].x).toBeCloseTo((g.positions[2].x-g.positions[0].x)/3);render(<DateChart label="Вес" points={points}/>);const slider=screen.getByRole('slider');expect(slider.getAttribute('max')).toBe('1');fireEvent.change(slider,{target:{value:'0'}});expect(slider.getAttribute('aria-valuetext')).toContain('01.10.2026');expect(screen.getByRole('status').textContent).toContain('01.10.2026');});
});
