import {DailyProvider,FocusDock} from './components/daily-ui';
import React from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter } from 'react-router-dom';
import { App } from './App';
import { GrowthProvider } from './components/growth-ui';
import { UpdatesProvider } from './components/updates';
import './styles.css';
import './components/design.css';
import {initializeAppearance} from './appearance';
import './dominion.css';
import './dominion-material.css';
initializeAppearance('windows');
createRoot(document.getElementById('root')!).render(<React.StrictMode><UpdatesProvider api={window.nexus.updates}><GrowthProvider api={window.nexus.growth}><DailyProvider api={window.nexus.daily} reminders={window.nexus.reminders}><HashRouter><App/><FocusDock/></HashRouter></DailyProvider></GrowthProvider></UpdatesProvider></React.StrictMode>);
