import {z} from './validation';
import {dateSchema} from './growth';
import {ensureDaily,records,put,numericId} from './daily-core';
import {localDay} from './domain';
import type {Snapshot} from './snapshot-sync';
export const careConfigSchema=z.object({habit_id:z.number().int().positive(),role:z.enum(['habit','care']),slots:z.array(z.object({id:z.string().uuid().optional(),label:z.string().trim().min(1).max(60),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),notify:z.boolean()})).max(8)}).strict();
export const careMarkSchema=z.object({slot_id:z.string().uuid(),day:dateSchema,done:z.boolean().nullable()}).strict();
export const careRoleSchema=z.object({habit_id:z.number().int().positive(),role:z.enum(['habit','care'])}).strict();
export type CareRole=z.infer<typeof careRoleSchema>;
export function saveCareRole(s:Snapshot,input:CareRole){ensureDaily(s);const x=careRoleSchema.parse(input);if(!records(s,'habits').some(h=>h.id===x.habit_id&&h.active))throw new Error('Пункт не найден.');put(s,'habit_preferences',{id:x.habit_id,role:x.role,updated_at:new Date().toISOString()});}
export type CareConfig=z.infer<typeof careConfigSchema>;
export type CareMark=z.infer<typeof careMarkSchema>;
export type CareSlot={id:string;habit_id:number;label:string;time:string;notify:number;active:number;created_at:string;updated_at:string};
export type CareCheck={id:string;slot_id:string;day:string;done:number;updated_at:string};
export type HabitPreference={id:number;role:'habit'|'care';updated_at:string};
export function careSlots(s:Snapshot,habitId:number,day=localDay()):CareSlot[]{return records(s,'care_slots').filter(x=>x.habit_id===habitId&&x.active&&String(x.created_at).slice(0,10)<=day).sort((a,b)=>String(a.time).localeCompare(String(b.time))) as unknown as CareSlot[];}
export function saveCareConfig(s:Snapshot,input:CareConfig){ensureDaily(s);const x=careConfigSchema.parse(input),habit=records(s,'habits').find(h=>h.id===x.habit_id&&h.active);if(!habit)throw new Error('Пункт не найден.');if(x.slots.length&&(habit.period!=='daily'||habit.kind!=='positive'||habit.format!=='boolean'))throw new Error('Отдельные выполнения доступны для ежедневных пунктов с отметкой да / нет.');const now=new Date().toISOString(),slots=records(s,'care_slots');
  for(const slot of x.slots)if(slot.id&&!slots.some(r=>r.id===slot.id&&r.habit_id===x.habit_id))throw new Error('Выполнение не найдено.');
  for(const slot of slots.filter(r=>r.habit_id===x.habit_id&&r.active&&!x.slots.some(v=>v.id===r.id)))Object.assign(slot,{active:0,updated_at:now});
  for(const slot of x.slots){const old=slots.find(r=>r.id===slot.id);put(s,'care_slots',{id:slot.id??crypto.randomUUID(),habit_id:x.habit_id,label:slot.label,time:slot.time,notify:Number(slot.notify),active:1,created_at:old?.created_at??now,updated_at:now});}
  put(s,'habit_preferences',{id:x.habit_id,role:x.role,updated_at:now});reconcileCareLogs(s);
}
export function reconcileCareLogs(s:Snapshot){for(const pref of records(s,'habit_preferences')){const habit=records(s,'habits').find(h=>h.id===pref.id);if(!habit||habit.period!=='daily'||habit.kind!=='positive')continue;const slots=careSlots(s,Number(habit.id)),ids=new Set(slots.map(x=>x.id));if(!ids.size)continue;const checks=records(s,'care_checks').filter(c=>ids.has(String(c.slot_id))&&slots.some(slot=>slot.id===c.slot_id&&slot.created_at.slice(0,10)<=String(c.day)));for(const day of new Set(checks.map(c=>String(c.day)))){const relevant=checks.filter(c=>c.day===day),done=relevant.filter(c=>c.done===1).length,total=slots.filter(slot=>slot.created_at.slice(0,10)<=day).length,list=records(s,'habit_logs'),old=list.find(l=>l.habit_id===habit.id&&l.day===day);put(s,'habit_logs',{id:old?.id??numericId(list),habit_id:habit.id,day,value:done===total?habit.target:0,status:done===total?'done':'missed',comment:`${done}/${total}`});}}}
export function markCare(s:Snapshot,input:CareMark){ensureDaily(s);const x=careMarkSchema.parse(input),slot=records(s,'care_slots').find(r=>r.id===x.slot_id&&r.active),habit=records(s,'habits').find(h=>h.id===slot?.habit_id&&h.active);if(!slot||!habit||habit.period!=='daily'||String(slot.created_at).slice(0,10)>x.day)throw new Error('Выполнение недоступно для этой даты.');const id=`${x.slot_id}:${x.day}`;if(x.done===null)s.tables.care_checks=records(s,'care_checks').filter(c=>c.id!==id);else put(s,'care_checks',{id,slot_id:x.slot_id,day:x.day,done:Number(x.done),updated_at:new Date().toISOString()});reconcileCareLogs(s);if(x.done===null&&!records(s,'care_checks').some(c=>careSlots(s,Number(habit.id),x.day).some(slot=>slot.id===c.slot_id)&&c.day===x.day)){const log=records(s,'habit_logs').find(l=>l.habit_id===habit.id&&l.day===x.day);if(log)Object.assign(log,{value:0,status:'skipped',comment:''});}}
export function knownCare(s:Snapshot,day=localDay()){return records(s,'care_slots').filter(x=>x.active&&String(x.created_at).slice(0,10)<=day&&records(s,'habits').some(h=>h.id===x.habit_id&&h.active&&h.period==='daily'&&h.kind==='positive'&&h.format==='boolean')).map(x=>({id:x.id,habitId:x.habit_id,name:records(s,'habits').find(h=>h.id===x.habit_id)?.name,label:x.label,time:x.time}));}
