import type {Snapshot} from './snapshot-sync';
import type {Habit,HabitLog,Account,Category,WeightEntry,DailyEntry} from './models';
import {localDay} from './domain';
import {records,shiftDay} from './daily-core';
import type {CareConfig,CareRole,CareMark,CareSlot,CareCheck,HabitPreference} from './care';
import type {RoutineInput,RoutineEntry,Routine} from './routines';
import type {PaymentInput,PaymentAction,ScheduledPayment,PaymentOccurrence} from './payments';
import {experimentResult,type ExperimentInput,type Experiment, type ExperimentLog, type experimentMarkSchema} from './experiments';
import type {FocusInput,FocusSession} from './focus';
import {eveningQuestion,type ReflectionInput,type EveningAnswer} from './reflection';
import type {z} from './validation';
export type DailyData={habits:Habit[];logs:HabitLog[];preferences:HabitPreference[];slots:CareSlot[];checks:CareCheck[];routines:Routine[];payments:ScheduledPayment[];occurrences:PaymentOccurrence[];accounts:Account[];categories:Category[];experiments:Experiment[];experimentLogs:ExperimentLog[];results:ReturnType<typeof experimentResult>[];sessions:FocusSession[];answers:EveningAnswer[];question:string;weights:WeightEntry[];health:DailyEntry[];journalDays:string[];tasks:{id:string;title:string;status:string;due_day:string}[]};
export interface DailyAPI{list():Promise<DailyData>;careConfig(x:CareConfig):Promise<void>;careRole(x:CareRole):Promise<void>;careMark(x:CareMark):Promise<void>;routine(x:RoutineInput):Promise<void>;routineEntry(x:RoutineEntry):Promise<void>;payment(x:PaymentInput):Promise<void>;paymentAction(x:PaymentAction):Promise<void>;experiment(x:ExperimentInput):Promise<void>;experimentMark(x:z.infer<typeof experimentMarkSchema>):Promise<void>;focus(x:FocusInput):Promise<void>;reflection(x:ReflectionInput):Promise<void>}
export function dailyData(s:Snapshot):DailyData{const experiments=records(s,'experiments') as unknown as Experiment[];return {habits:records(s,'habits') as unknown as Habit[],logs:records(s,'habit_logs') as unknown as HabitLog[],preferences:records(s,'habit_preferences') as unknown as HabitPreference[],slots:records(s,'care_slots') as unknown as CareSlot[],checks:records(s,'care_checks') as unknown as CareCheck[],routines:records(s,'routines') as unknown as Routine[],payments:records(s,'scheduled_payments') as unknown as ScheduledPayment[],occurrences:records(s,'payment_occurrences') as unknown as PaymentOccurrence[],accounts:records(s,'finance_accounts') as unknown as Account[],categories:records(s,'finance_categories') as unknown as Category[],experiments,experimentLogs:records(s,'experiment_logs') as unknown as ExperimentLog[],results:experiments.map(e=>experimentResult(s,e)),sessions:records(s,'focus_sessions') as unknown as FocusSession[],answers:records(s,'evening_answers') as unknown as EveningAnswer[],question:eveningQuestion(s,localDay()),journalDays:records(s,'daily_journals').filter(x=>String(x.raw_text??'').trim()).map(x=>String(x.day)),weights:records(s,'weight_entries') as unknown as WeightEntry[],health:records(s,'health_daily_entries') as unknown as DailyEntry[],tasks:records(s,'day_tasks') as unknown as DailyData['tasks']};}
export function dailyCoachFacts(s:Snapshot,start:string,end:string){const range=(table:string)=>(s.tables[table]??[]).filter(r=>String(r.day)>=start&&String(r.day)<=end);return {care:range('care_checks').map(c=>({day:c.day,habit:s.tables.habits?.find(h=>h.id===s.tables.care_slots?.find(slot=>slot.id===c.slot_id)?.habit_id)?.name,execution:s.tables.care_slots?.find(slot=>slot.id===c.slot_id)?.label,done:c.done===1})),focus:range('focus_sessions').filter(x=>x.state==='finished').map(x=>({title:x.title,day:x.day,minutes:Math.round(Number(x.elapsed_seconds)/60)})),reflections:range('evening_answers').filter(x=>!x.skipped&&x.answer),experiments:(s.tables.experiments??[]).filter(x=>String(x.start_day)<=end&&shiftDay(String(x.start_day),Math.max(0,Number(x.duration)-1))>=start).map(x=>({title:x.title,rule:x.rule,marks:range('experiment_logs').filter(l=>l.experiment_id===x.id)})),payments:(s.tables.payment_occurrences??[]).filter(x=>String(x.due_day)<=end&&x.status==='open').map(x=>({name:s.tables.scheduled_payments?.find(p=>p.id===x.payment_id)?.name,due_day:x.due_day,amount_cents:x.amount_cents}))};}
