import { describe,it,expect } from 'vitest';
import { saveGoal,savePlan,saveRepeat,materializeRepeats,removeTask,saveMetric,saveMetricEntry,filterMetricSuggestions,knownMetrics,occurrenceId } from './growth';
import { mergeSnapshots } from './snapshot-sync';
import type { Snapshot } from './snapshot-sync';
import { insights,findPatterns } from './insights';
import { defaultReminders,reminderPlan } from './reminders';
const id='20000000-0000-4000-8000-000000000001',metricId='20000000-0000-4000-8000-000000000002';
const fresh=():Snapshot=>({format:'nexus-backup',version:7,exportedAt:'',tables:{}});
describe('weekly planning and repeats',()=>{
it('schedules the same plan without duplicate tasks and preserves completion',()=>{const s=fresh();savePlan(s,{id,title:'Уборка',week:'2026-09-28',scheduled_day:'2026-10-02',status:'done'});const task=s.tables.day_tasks[0];savePlan(s,{id,title:'Уборка',week:'2026-09-28',scheduled_day:'2026-10-03',status:'done'});expect(s.tables.day_tasks).toHaveLength(1);expect(s.tables.day_tasks[0]).toMatchObject({id:task.id,status:'done',due_day:'2026-10-03'});expect(()=>savePlan(s,{id,title:'Уборка',week:'2026-09-28',scheduled_day:'2026-10-05',status:'done'})).toThrow();});
it('generates stable occurrences, never resurrects a deleted one, and keeps a moved task',()=>{const s=fresh();saveRepeat(s,{id,title:'Тренировка',start_day:'2026-09-28',weekdays:[0,2,4],active:1});materializeRepeats(s,'2026-10-03');const task=s.tables.day_tasks.find(x=>x.due_day==='2026-10-02')!;task.due_day='2026-10-04';materializeRepeats(s,'2026-10-03');expect(s.tables.day_tasks.filter(x=>x.id===task.id)).toHaveLength(1);removeTask(s,String(task.id));materializeRepeats(s,'2026-10-03');expect(s.tables.day_tasks.some(x=>x.id===task.id)).toBe(false);expect(s.tables.recurring_skips).toHaveLength(1);});
it('does not overwrite a completed occurrence generated independently on another device',()=>{const base=fresh(),left=fresh(),right=fresh();for(const s of [left,right]){saveRepeat(s,{id,title:'Уборка',start_day:'2026-10-03',weekdays:[5],active:1});materializeRepeats(s,'2026-10-03');}const task=right.tables.day_tasks.find(x=>x.id===occurrenceId(id,'2026-10-03'))!;task.status='done';const merged=mergeSnapshots(base,left,right).snapshot;expect(merged.tables.day_tasks.find(x=>x.id===task.id)?.status).toBe('done');removeTask(right,String(task.id));expect(mergeSnapshots(base,left,right).snapshot.tables.day_tasks.some(x=>x.id===task.id)).toBe(false);});
});
it('keeps goal bookkeeping separate from account balances',()=>{const s=fresh();s.tables.finance_accounts=[{id:1,opening_cents:50000}];saveGoal(s,{name:'Отпуск',target_cents:100000,saved_cents:25000,deadline:null,active:1});expect(s.tables.finance_accounts[0].opening_cents).toBe(50000);expect(s.tables.finance_transactions).toBeUndefined();expect(s.version).toBe(8);});
it('validates custom metric types, choices and absent values',()=>{const s=fresh();saveMetric(s,{id:metricId,name:'Кофе',kind:'number',unit:'чашек',options:[],active:1});saveMetricEntry(s,{metric_id:metricId,day:'2026-10-03',value:0});expect(s.tables.metric_entries[0].value_json).toBe('0');expect(()=>saveMetricEntry(s,{metric_id:metricId,day:'2026-10-03',value:'много'})).toThrow();expect(()=>saveMetric(s,{id:metricId,name:'Кофе',kind:'boolean',unit:'',options:[],active:1})).toThrow();expect(filterMetricSuggestions(knownMetrics(s),[{metricId,value:0},{metricId:id,value:2},{metricId,value:3}])).toEqual([{metricId,value:0}]);saveMetricEntry(s,{metric_id:metricId,day:'2026-10-03',value:null});expect(s.tables.metric_entries).toHaveLength(0);});
it('compares matching weekdays without treating missing measurements as zero',()=>{const s=fresh();s.tables.health_daily_entries=[{day:'2026-09-28',sleep_minutes:480},{day:'2026-09-21',sleep_minutes:420},{day:'2026-09-22',sleep_minutes:null},{day:'2026-09-27',sleep_minutes:100}];const stats=insights(s,'2026-09-28','2026-09-29');expect(stats.previousEnd).toBe('2026-09-22');expect(stats.current.sleep).toBe(480);expect(stats.previous.sleep).toBe(420);expect(findPatterns(s)).toEqual([]);});
it('requires enough paired observations for patterns and never infers a missing metric',()=>{const s=fresh();saveMetric(s,{id:metricId,name:'Игры',kind:'number',unit:'мин',options:[],active:1});s.tables.health_daily_entries=[];for(let i=1;i<=14;i++){const day=`2026-09-${String(i).padStart(2,'0')}`;s.tables.health_daily_entries.push({day,sleep_minutes:i<=7?360:480});saveMetricEntry(s,{metric_id:metricId,day,value:i<=7?120:0});}expect(findPatterns(s,'2026-10-03')).toHaveLength(1);s.tables.metric_entries.splice(5);expect(findPatterns(s,'2026-10-03')).toHaveLength(0);});
describe('custom notifications',()=>{
it('keeps both medicine times even when the morning habit has been marked',()=>{const s=fresh();s.tables.habits=[{id:1,name:'Уход',kind:'positive',period:'daily',active:1,target:1}];s.tables.habit_logs=[{habit_id:1,day:'2026-10-03',value:1,status:'done'}];const settings={...defaultReminders,quiet:false,rules:[{id,title:'Уход',body:'Пора заняться уходом.',times:['09:00','20:00'],weekdays:[5],habitId:1,skipCompleted:false,enabled:true}]};const plan=reminderPlan(s,settings,new Date('2026-10-03T08:00:00'));expect(plan.filter(x=>x.id.endsWith('2026-10-03')).map(x=>new Date(x.at).getHours())).toEqual([9,20]);settings.rules[0].skipCompleted=true;expect(reminderPlan(s,settings,new Date('2026-10-03T08:00:00')).some(x=>x.id.endsWith('2026-10-03'))).toBe(false);});
it('moves a late reminder out of quiet hours and updates weekday for native recurrence',()=>{const s=fresh(),settings={...defaultReminders,rules:[{id,title:'Напомни',body:'Пора.',times:['23:00'],weekdays:[5],habitId:null,skipCompleted:false,enabled:true}]};const reminder=reminderPlan(s,settings,new Date('2026-10-03T18:00:00'))[0];expect(new Date(reminder.at).getHours()).toBe(8);expect(reminder.repeatDays).toEqual([6]);});
it('suppresses journal reminders when a record already exists',()=>{const s=fresh();s.tables.daily_journals=[{day:'2026-10-03',raw_text:'Записал день'}];expect(reminderPlan(s,{...defaultReminders,journal:true},new Date('2026-10-03T18:00:00')).some(x=>x.id==='journal:2026-10-03')).toBe(false);});
});
