import type { Snapshot,Row } from './snapshot-sync';
import { localDay,habitSuccess } from './domain';
import { growthData,metricValue } from './growth';
import type { Habit,HabitLog } from './models';
export type PeriodStats={focusMinutes?:number;expense:number;income:number;sleep:number|null;sleepDays:number;habitRate:number|null;habitMarks:number;doneTasks:number;weight:number|null;metrics:{id:string;name:string;unit:string;average:number;days:number}[]};
export type Pattern={id:string;text:string;sample:number;detail:string};
export type Insights={current:PeriodStats;previous:PeriodStats;previousStart:string;previousEnd:string;patterns:Pattern[]};
const shift=(day:string,n:number)=>{const date=new Date(`${day}T12:00:00`);date.setDate(date.getDate()+n);return localDay(date);};
const avg=(values:number[])=>values.length?values.reduce((sum,v)=>sum+v,0)/values.length:null;
export function periodStats(s:Snapshot,start:string,end:string):PeriodStats{const range=(table:string,key='day')=>(s.tables[table]??[]).filter(r=>String(r[key]).slice(0,10)>=start&&String(r[key]).slice(0,10)<=end);const finance=range('finance_transactions','occurred_at'),sleep=range('health_daily_entries').map(x=>x.sleep_minutes).filter((x):x is number=>typeof x==='number'),weights=range('weight_entries').sort((a,b)=>String(a.day).localeCompare(String(b.day)));const habits=(s.tables.habits??[]) as unknown as Habit[],logs=range('habit_logs').filter(x=>x.status!=='skipped') as unknown as HabitLog[];const relevant=logs.filter(l=>habits.some(h=>h.id===l.habit_id&&h.active&&h.period==='daily'));const data=growthData(s);
  return {focusMinutes:range('focus_sessions').filter(x=>x.state==='finished').reduce((n,x)=>n+Number(x.elapsed_seconds)/60,0),expense:finance.filter(x=>x.type==='expense').reduce((sum,x)=>sum+Number(x.amount_cents),0),income:finance.filter(x=>x.type==='income').reduce((sum,x)=>sum+Number(x.amount_cents),0),sleep:avg(sleep),sleepDays:sleep.length,habitRate:relevant.length?relevant.filter(l=>habitSuccess(habits.find(h=>h.id===l.habit_id)!,l)).length/relevant.length:null,habitMarks:relevant.length,doneTasks:range('day_tasks','due_day').filter(x=>x.status==='done').length,weight:weights.length?Number(weights.at(-1)!.weight_kg):null,metrics:data.metrics.filter(x=>x.active&&x.kind==='number').flatMap(m=>{const values=data.entries.filter(x=>x.metric_id===m.id&&x.day>=start&&x.day<=end).map(metricValue).filter((x):x is number=>typeof x==='number');return values.length?[{id:m.id,name:m.name,unit:m.unit,average:avg(values)!,days:values.length}]:[];})};
}
export function findPatterns(s:Snapshot,today=localDay()):Pattern[]{const from=shift(today,-89),days=(s.tables.health_daily_entries??[]).filter(x=>String(x.day)>=from&&String(x.day)<=today);const patterns:Pattern[]=[];
  const compare=(id:string,a:number[],b:number[],labelA:string,labelB:string)=>{if(a.length<5||b.length<5)return;const left=avg(a)!,right=avg(b)!,delta=left-right;if(Math.abs(delta)<30)return;const time=(n:number)=>`${Math.floor(Math.round(n)/60)} ч ${Math.round(n)%60} мин`;patterns.push({id,text:`${labelA}: сон в среднем ${time(left)}. ${labelB}: ${time(right)}.`,sample:a.length+b.length,detail:`${a.length} и ${b.length} записей. Это совпадение в данных, не доказательство причины.`});};
  const contexts=(s.tables.day_details??[]).filter(x=>String(x.day)>=from&&String(x.day)<=today);for(const tag of ['Игры','Прогулка','Работа']){const marked=new Set(contexts.filter(x=>contextsFrom(x).includes(tag)).map(x=>x.day)),unmarked=new Set(contexts.filter(x=>contextsFrom(x).length&&!contextsFrom(x).includes(tag)).map(x=>x.day));compare(`context:${tag}`,days.filter(x=>marked.has(x.day)&&typeof x.sleep_minutes==='number').map(x=>Number(x.sleep_minutes)),days.filter(x=>unmarked.has(x.day)&&typeof x.sleep_minutes==='number').map(x=>Number(x.sleep_minutes)),`В дни с контекстом «${tag}»`,'В другие отмеченные дни');}
  const data=growthData(s);for(const metric of data.metrics.filter(x=>x.active&&x.kind==='number')){const pairs=data.entries.filter(x=>x.metric_id===metric.id&&x.day>=from&&x.day<=today).flatMap(entry=>{const value=metricValue(entry),sleep=days.find(x=>x.day===entry.day)?.sleep_minutes;return typeof value==='number'&&typeof sleep==='number'?[{value,sleep}]:[];});if(pairs.length<14)continue;const values=pairs.map(x=>x.value).sort((a,b)=>a-b),median=(values[Math.floor((values.length-1)/2)]+values[Math.floor(values.length/2)])/2;compare(`metric:${metric.id}`,pairs.filter(x=>x.value>median).map(x=>x.sleep),pairs.filter(x=>x.value<=median).map(x=>x.sleep),`«${metric.name}» выше ${median} ${metric.unit}`.trim(),`«${metric.name}» до ${median} ${metric.unit}`.trim());}
  const rested=days.filter(x=>typeof x.sleep_minutes==='number'&&typeof x.energy==='number');if(rested.length>=14){const longer=rested.filter(x=>Number(x.sleep_minutes)>=420),shorter=rested.filter(x=>Number(x.sleep_minutes)<420);if(longer.length>=5&&shorter.length>=5){const a=longer.filter(x=>Number(x.energy)>=7).length/longer.length,b=shorter.filter(x=>Number(x.energy)>=7).length/shorter.length;if(Math.abs(a-b)>=0.25)patterns.push({id:'sleep:energy',text:`При сне от 7 часов высокая энергия отмечена в ${Math.round(a*100)}% записей; при более коротком сне — в ${Math.round(b*100)}%.`,sample:rested.length,detail:'Связь в твоих записях, а не медицинский вывод.'});}}
  return patterns.sort((a,b)=>b.sample-a.sample).slice(0,4);
}
export function insights(s:Snapshot,start:string,end:string):Insights{const previousStart=shift(start,-7),previousEnd=shift(end,-7);return {current:periodStats(s,start,end),previous:periodStats(s,previousStart,previousEnd),previousStart,previousEnd,patterns:findPatterns(s,end)};}
export function contextsFrom(row:Row):string[]{try{const x:unknown=JSON.parse(String(row.contexts_json));return Array.isArray(x)?x.filter((v):v is string=>typeof v==='string'):[];}catch{return [];}}
