import {z} from './validation';
import {dateSchema,occurrenceId} from './growth';
import {ensureDaily,records,put,shiftDay} from './daily-core';
import {localDay} from './domain';
import {nextTransactionCreatedAt} from './finance-order';
import type {Snapshot} from './snapshot-sync';
export const paymentSchema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1).max(120),amount_cents:z.number().int().positive().safe(),account_id:z.number().int().positive(),category_id:z.number().int().positive(),cadence:z.enum(['weekly','monthly','yearly']),start_day:dateSchema,active:z.union([z.literal(0),z.literal(1)])}).strict();
export const paymentActionSchema=z.object({id:z.string().min(1).max(80),action:z.enum(['pay','skip']),day:dateSchema,amount_cents:z.number().int().positive().safe().optional(),account_id:z.number().int().positive().optional(),category_id:z.number().int().positive().optional()}).strict();
export type PaymentInput=z.infer<typeof paymentSchema>;
export type PaymentAction=z.infer<typeof paymentActionSchema>;
export type ScheduledPayment=Omit<PaymentInput,'id'>&{id:string;updated_at:string};
export type PaymentOccurrence={id:string;payment_id:string;due_day:string;amount_cents:number;account_id:number;category_id:number;status:'open'|'paid'|'skipped';transaction_id:number|null;updated_at:string};
function validParents(s:Snapshot,account:number,category:number){if(!records(s,'finance_accounts').some(r=>r.id===account&&r.active)||!records(s,'finance_categories').some(r=>r.id===category&&r.active&&r.kind==='expense'))throw new Error('Выберите активный счёт и категорию расхода.');}
export function savePayment(s:Snapshot,input:PaymentInput){ensureDaily(s);const x=paymentSchema.parse(input);if(x.active)validParents(s,x.account_id,x.category_id);put(s,'scheduled_payments',{...x,id:x.id??crypto.randomUUID(),updated_at:new Date().toISOString()});materializePayments(s);}
export function paymentDate(anchor:string,cadence:PaymentInput['cadence'],index:number):string{if(cadence==='weekly')return shiftDay(anchor,index*7);const original=new Date(`${anchor}T12:00:00`),month=original.getMonth()+index*(cadence==='yearly'?12:1),last=new Date(original.getFullYear(),month+1,0,12).getDate();return localDay(new Date(original.getFullYear(),month,Math.min(original.getDate(),last),12));}
export function materializePayments(s:Snapshot,today=localDay()):boolean{let changed=false;const through=shiftDay(today,30);for(const p of records(s,'scheduled_payments').filter(x=>x.active) as unknown as ScheduledPayment[])for(let i=0;i<2000;i++){const day=paymentDate(p.start_day,p.cadence,i);if(day>through)break;const id=`${p.id}:${day}`;if(records(s,'payment_occurrences').some(r=>r.id===id))continue;put(s,'payment_occurrences',{id,payment_id:p.id,due_day:day,amount_cents:p.amount_cents,account_id:p.account_id,category_id:p.category_id,status:'open',transaction_id:null,updated_at:new Date().toISOString()});changed=true;}return changed;}
export function paymentAction(s:Snapshot,input:PaymentAction){ensureDaily(s);const x=paymentActionSchema.parse(input),occ=records(s,'payment_occurrences').find(r=>r.id===x.id);if(!occ)throw new Error('Платёж не найден.');if(occ.status!=='open')return;const now=new Date().toISOString();if(x.action==='skip'){Object.assign(occ,{status:'skipped',updated_at:now});return;}const account=x.account_id??Number(occ.account_id),category=x.category_id??Number(occ.category_id);validParents(s,account,category);const p=records(s,'scheduled_payments').find(r=>r.id===occ.payment_id);if(!p)throw new Error('Платёж не найден.');const id=parseInt(occurrenceId(String(p.id),String(occ.due_day)).replaceAll('-','').slice(0,12),16)||1,list=records(s,'finance_transactions'),existing=list.find(r=>r.id===id);if(existing&&existing.note!==`Оплата: ${p.name}`)throw new Error('Не удалось записать платёж. Повторите позже.');if(!existing)list.push({id,created_at:nextTransactionCreatedAt(list),occurred_at:`${x.day}T12:00:00`,amount_cents:x.amount_cents??occ.amount_cents,type:'expense',account_id:account,target_account_id:null,category_id:category,note:`Оплата: ${p.name}`});Object.assign(occ,{status:'paid',account_id:account,category_id:category,amount_cents:x.amount_cents??occ.amount_cents,transaction_id:id,updated_at:now});}
