import { z } from './validation';
import { habitDueToday,habitSuccess,localDay } from './domain';
import type { Snapshot } from './snapshot-sync';
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
export const reminderRuleSchema=z.object({id:z.string().uuid(),title:z.string().trim().min(1).max(120),body:z.string().trim().min(1).max(300),times:z.array(time).min(1).max(8),weekdays:z.array(z.number().int().min(0).max(6)).min(1).max(7),habitId:z.number().int().positive().nullable(),skipCompleted:z.boolean(),enabled:z.boolean()}).strict();
export const reminderSchema=z.object({rules:z.array(reminderRuleSchema).max(30).default([]),tasksText:z.string().trim().min(1).max(300).default('План сам себя не выполнит. Открой NEXUS.'),journalText:z.string().trim().min(1).max(300).default('Не оставляй день без записи. Две минуты — и готово.'),weeklyText:z.string().trim().min(1).max(300).default('Неделя закончилась. Разбери результат и выбери следующий шаг.'),tasks:z.boolean(),tasksTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),journal:z.boolean(),journalTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),weekly:z.boolean(),weeklyTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),weeklyDay:z.number().int().min(0).max(6),quiet:z.boolean(),quietStart:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),quietEnd:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)}).strict();
export type ReminderRule=z.infer<typeof reminderRuleSchema>;
export type ReminderSettings=z.infer<typeof reminderSchema>;
export const defaultReminders:ReminderSettings={rules:[],tasksText:'План сам себя не выполнит. Открой NEXUS.',journalText:'Не оставляй день без записи. Две минуты — и готово.',weeklyText:'Неделя закончилась. Разбери результат и выбери следующий шаг.',tasks:false,tasksTime:'09:00',journal:false,journalTime:'21:00',weekly:false,weeklyTime:'20:00',weeklyDay:6,quiet:true,quietStart:'22:00',quietEnd:'08:00'};
export interface ReminderAPI{get():Promise<{settings:ReminderSettings;enabled:boolean;exact?:boolean}>;save(settings:ReminderSettings):Promise<void>;permission():Promise<{enabled:boolean}>;precision?():Promise<void>}
export type Reminder={id:string;at:number;title:string;body:string;ruleId:string;repeatDays:number[];time:string;habitId?:number|null;skipCompleted?:boolean};
const minute=(time:string)=>{const [h,m]=time.split(':').map(Number);return h*60+m;};
export function quietTime(date:Date,settings:ReminderSettings){if(!settings.quiet)return false;const start=minute(settings.quietStart),end=minute(settings.quietEnd),time=date.getHours()*60+date.getMinutes();return start===end?true:start<end?time>=start&&time<end:time>=start||time<end;}
export function reminderPlan(s:Snapshot,settings:ReminderSettings,now=new Date()):Reminder[]{const result:Reminder[]=[];
  const add=(type:string,date:Date,time:string,title:string,body:string,repeatDays=[0,1,2,3,4,5,6],habitId?:number|null,skipCompleted?:boolean)=>{const at=new Date(date);at.setHours(Math.floor(minute(time)/60),minute(time)%60,0,0);if(at.getTime()<=now.getTime())return;const intendedDay=localDay(at);if(quietTime(at,settings)){if(settings.quietStart===settings.quietEnd)return;const end=minute(settings.quietEnd);at.setHours(Math.floor(end/60),end%60,0,0);if(at.getTime()<new Date(`${intendedDay}T${time}`).getTime())at.setDate(at.getDate()+1);if(localDay(at)!==intendedDay)repeatDays=repeatDays.map(d=>(d+1)%7);}result.push({id:`${type}:${intendedDay}`,at:at.getTime(),title,body,ruleId:type,repeatDays,time:`${String(at.getHours()).padStart(2,'0')}:${String(at.getMinutes()).padStart(2,'0')}`,habitId,skipCompleted});};
  for(let offset=0;offset<7;offset++){const date=new Date(now);date.setDate(date.getDate()+offset);const day=localDay(date);if(settings.tasks){const tasks=(s.tables.day_tasks??[]).filter(x=>x.status==='open'&&String(x.due_day)<=day);if(tasks.length)add('tasks',date,settings.tasksTime,'План на день',settings.tasksText);}if(settings.journal){const recorded=(s.tables.daily_journals??[]).some(x=>x.day===day&&String(x.raw_text).trim())||(s.tables.day_details??[]).some(x=>x.day===day&&String(x.achievement).trim());if(!recorded)add('journal',date,settings.journalTime,'Как прошёл день?',settings.journalText);}if(settings.weekly&&(date.getDay()+6)%7===settings.weeklyDay)add('weekly',date,settings.weeklyTime,'Итоги недели',settings.weeklyText,[settings.weeklyDay]);}
  for(const rule of settings.rules.filter(x=>x.enabled)){const habit=rule.habitId?(s.tables.habits??[]).find(h=>h.id===rule.habitId&&h.active):null;if(rule.habitId&&!habit)continue;for(let offset=0;offset<8;offset++){const date=new Date(now);date.setDate(date.getDate()+offset);const day=localDay(date);if(!rule.weekdays.includes((date.getDay()+6)%7))continue;if(habit&&rule.skipCompleted){const h=habit as unknown as import('./models').Habit,logs=(s.tables.habit_logs??[]) as unknown as import('./models').HabitLog[];if(h.period==='weekly'?!habitDueToday(h,logs,day):habitSuccess(h,logs.find(l=>l.habit_id===h.id&&l.day===day)))continue;}for(const time of [...new Set(rule.times)])add(`rule:${rule.id}:${time}`,date,time,rule.title,rule.body,rule.weekdays,rule.habitId,rule.skipCompleted);}}
  for(const slot of s.tables.care_slots??[]){if(!slot.active||!slot.notify)continue;const habit=s.tables.habits?.find(h=>h.id===slot.habit_id&&h.active);if(!habit||habit.period!=='daily')continue;for(let offset=0;offset<8;offset++){const date=new Date(now);date.setDate(date.getDate()+offset);const day=localDay(date);if(s.tables.care_checks?.some(c=>c.slot_id===slot.id&&c.day===day&&c.done===1))continue;add(`care:${slot.id}`,date,String(slot.time),`${habit.name} · ${slot.label}`.slice(0,120),'Время пришло. Сделай и отметь выполнение.');}}
  return result.sort((a,b)=>a.at-b.at);
}
