import { Capacitor,registerPlugin } from '@capacitor/core';
import { defaultReminders,reminderSchema,reminderPlan,type ReminderAPI,type Reminder,type ReminderSettings } from '../../NEXUS/src/shared/reminders';
import { habitDueToday,habitSuccess,localDay } from '../../NEXUS/src/shared/domain';
import type { Snapshot } from '../../NEXUS/src/shared/snapshot-sync';
import type { Habit,HabitLog } from '../../NEXUS/src/shared/models';
import { connection } from './sync';
const native=registerPlugin<{status():Promise<{enabled:boolean;exact:boolean}>;permission():Promise<{enabled:boolean}>;precision():Promise<void>;schedule(input:{plan:Reminder[];state:Record<string,unknown>}):Promise<void>}>('NexusReminders');
let latest:Snapshot|null=null,last='';let tail=Promise.resolve();
function key(){let hash=2166136261;for(const char of connection().token)hash=Math.imul(hash^char.charCodeAt(0),16777619);return `nexus.reminders.${hash>>>0}`;}
function read():ReminderSettings{try{return reminderSchema.parse(JSON.parse(localStorage.getItem(key())??'null'));}catch{return defaultReminders;}}
function schedule(snapshot:Snapshot|null,settings=read()):Promise<void>{if(!Capacitor.isNativePlatform())return Promise.resolve();const s=snapshot??{format:'nexus-backup' as const,version:9,exportedAt:'',tables:{}};const seen=new Set<string>(),plan=reminderPlan(s,settings).filter(x=>{if(seen.has(x.ruleId))return false;seen.add(x.ruleId);return true;}),habits=(s.tables.habits??[]) as unknown as Habit[],logs=(s.tables.habit_logs??[]) as unknown as HabitLog[],completedHabits:Record<string,string[]>={};for(const h of habits){completedHabits[h.id]=[];for(let offset=0;offset<8;offset++){const d=new Date();d.setDate(d.getDate()+offset);const day=localDay(d);if(h.period==='weekly'?!habitDueToday(h,logs,day):habitSuccess(h,logs.find(x=>x.habit_id===h.id&&x.day===day)))completedHabits[h.id].push(day);}}
const state={quiet:settings.quiet,quietStart:settings.quietStart,quietEnd:settings.quietEnd,journalDays:[...(s.tables.daily_journals??[]).filter(x=>String(x.raw_text).trim()).map(x=>x.day),...(s.tables.day_details??[]).filter(x=>String(x.achievement).trim()).map(x=>x.day)],tasks:(s.tables.day_tasks??[]).map(x=>({due_day:x.due_day,status:x.status})),completedHabits,completedCare:(s.tables.care_checks??[]).filter(c=>c.done===1).map(c=>({slot_id:c.slot_id,day:c.day}))};const signature=JSON.stringify({plan:plan.map(x=>({...x,at:Math.floor(x.at/60_000)})),state});if(signature===last)return tail;tail=tail.catch(()=>{}).then(async()=>{await native.schedule({plan,state});last=signature;});return tail;}
export function updateReminders(snapshot:Snapshot|null){latest=snapshot;void schedule(snapshot).catch(()=>{});}
export const reminders:ReminderAPI={get:async()=>({settings:read(),...(Capacitor.isNativePlatform()?await native.status():{enabled:false})}),save:async settings=>{const parsed=reminderSchema.parse(settings);localStorage.setItem(key(),JSON.stringify(parsed));last='';await schedule(latest,parsed);},permission:async()=>Capacitor.isNativePlatform()?native.permission():{enabled:false},precision:async()=>{if(Capacitor.isNativePlatform())await native.precision();last='';}};
