import { askConfirm } from '../confirm';
import { GroupedNumberInput } from '../../shared/grouped-number';
import { displayDay } from '../../shared/domain';
import { useState } from 'react';
import { localDay, money, toSignedCents } from '../../shared/domain';
import { investmentSummary } from '../../shared/investments';
import { Empty, Field, LineChart, Modal, Panel, Stat, errorText, useData } from '../ui';

export function InvestmentsPanel(){
  const [creating,setCreating]=useState(false);
  const {data,error,reload}=useData(window.nexus.investments.list);
  const {data:settings}=useData(window.nexus.settings.get);
  const [account,setAccount]=useState(''),[name,setName]=useState(''),[day,setDay]=useState(localDay()),[value,setValue]=useState(''),[flow,setFlow]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const accounts=data?.accounts.filter(x=>x.active)??[],selected=Number(account)||accounts[0]?.id;
  const entries=data?.entries.filter(x=>x.account_id===selected)??[],summary=investmentSummary(entries);
  const fmt=(cents:number)=>money(cents,settings?.currency??'RUB');
  async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await reload();}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
  return <div className="content-grid"><Panel title="Инвестиции" action={<button className="button small ghost" onClick={()=>setCreating(true)}>+ Портфель</button>}>{(error||message)&&<p className="help-warning">{error||message}</p>}
    <Field label="Портфель"><select value={selected??''} onChange={e=>setAccount(e.target.value)}><option value="">Выберите портфель</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
    {!accounts.length&&<Empty title="Портфелей пока нет" action={<button className="button secondary" onClick={()=>setCreating(true)}>Создать портфель</button>}/>}
    {creating&&<Modal title="Новый портфель" onClose={()=>setCreating(false)}><form className="form-stack" onSubmit={e=>{e.preventDefault();void act(async()=>{await window.nexus.investments.saveAccount({name:name.trim(),active:1});const updated=await window.nexus.investments.list();setAccount(String(updated.accounts.find(a=>a.name===name.trim())?.id??''));setName('');setCreating(false);});}}><Field label="Название"><input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Например, брокерский счёт"/></Field><button className="button primary" disabled={busy||!name.trim()}>Создать портфель</button></form></Modal>}
    {selected&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void act(async()=>{const cents=toSignedCents(value);if(cents<0)throw new Error('Стоимость портфеля не может быть отрицательной.');await window.nexus.investments.saveEntry({account_id:selected,day,value_cents:cents,flow_cents:flow.trim()?toSignedCents(flow):0,note});setValue('');setFlow('');setNote('');});}}><div className="form-grid two"><Field label="Дата"><input required type="date" max={localDay()} value={day} onChange={e=>setDay(e.target.value)}/></Field><Field label="Полная стоимость, ₽"><GroupedNumberInput required value={value} onValueChange={setValue}/></Field></div><Field label="Пополнение (+) / вывод (−) за этот день, ₽" hint="Необязательно. Без движения денег оставьте пустым. Первая оценка считается стартовой стоимостью."><GroupedNumberInput value={flow} onValueChange={setFlow} placeholder="Например, 5000 или −2000"/></Field><Field label="Комментарий"><input value={note} onChange={e=>setNote(e.target.value)}/></Field><button className="button primary" disabled={busy||!value.trim()}>Записать оценку дня</button><small className="muted">Повторная запись за ту же дату заменяет предыдущую оценку.</small></form>}
  </Panel><Panel title={accounts.find(x=>x.id===selected)?.name??'Динамика портфеля'}>{entries.length?<><div className="stats-grid"><Stat label="Стоимость" value={fmt(summary.value)}/><Stat label="Пополнения минус выводы" value={fmt(summary.flow)} sub="После первой оценки"/><Stat label="Результат инвестиций" value={fmt(summary.profit)} sub="Изменение стоимости без внесённых денег"/></div><LineChart values={entries.map(x=>x.value_cents)} labels={entries.map(x=>x.day)} formatValue={fmt}/><div className="compact-list">{[...entries].reverse().slice(0,20).map(x=><div key={x.id}><span>{displayDay(x.day)}</span><strong>{fmt(x.value_cents)}</strong><span>{x.flow_cents?`Движение: ${fmt(x.flow_cents)}`:x.note}</span><button className="button small ghost" onClick={()=>{setDay(x.day);setValue(String(x.value_cents/100));setFlow(String(x.flow_cents/100));setNote(x.note);}}>Изменить</button><button className="button small ghost" disabled={busy} onClick={async ()=>{if((await askConfirm('Удалить оценку за этот день?')))void act(()=>window.nexus.investments.deleteEntry(x.id));}}>Удалить</button></div>)}</div></>:<Empty title="Оценок пока нет"/>}</Panel></div>;
}
