import { hasIncompleteSelectedFinance } from '../../shared/journal-schema';
import { askConfirm } from '../confirm';
import { JournalReview } from '../components/journal-review';
import { useEffect, useRef, useState } from 'react';
import { localDay } from '../../shared/domain';
import { type JournalAnalysis, type JournalEntry } from '../../shared/models';
import { useAutoSave } from '../autosave';
import { Empty, Field, Notice, Panel, SaveIndicator, errorText, useData } from '../ui';

const parseAnalysis=(entry:JournalEntry|null):JournalAnalysis|null=>{if(!entry?.analysis_json)return null;try{return JSON.parse(entry.analysis_json) as JournalAnalysis;}catch{return null;}};
function asBase64(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(new Error('Не удалось прочитать запись.'));reader.readAsDataURL(blob);});}
export function JournalPanel({onApplied}:{onApplied:()=>void}){
  const {data,reload}=useData(window.nexus.journal.list),settings=useData(window.nexus.settings.get),health=useData(window.nexus.health.list),finance=useData(window.nexus.finance.list),work=useData(window.nexus.work.list);
  const [selectedId,setSelectedId]=useState<number|null>(null),[day,setDay]=useState(localDay()),[draft,setDraft]=useState(''),[source,setSource]=useState<'text'|'voice'>('text'),[keys,setKeys]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(''),[recording,setRecording]=useState(false),[notice,setNotice]=useState('');
  const [edited,setEdited]=useState<{id:number;value:JournalAnalysis}|null>(null);
  const {queue,status:saveStatus}=useAutoSave();
  const entryIdRef=useRef<number|null>(null),draftRef=useRef('');
  const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const selected=data?.find(x=>x.id===selectedId)??null,analysis=edited?.id===selectedId?edited.value:parseAnalysis(selected),applied=new Set(selected?JSON.parse(selected.applied_json) as string[]:[]);
  useEffect(()=>{return()=>{if(timer.current)clearTimeout(timer.current);if(recorder.current){recorder.current.onstop=null;if(recorder.current.state==='recording')recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());};},[]);
  async function select(entry:JournalEntry){setEdited(null);if(!await queue.flushAll()){setNotice('Исправьте ошибку сохранения перед переходом к другой записи.');return;}entryIdRef.current=entry.id;draftRef.current=entry.raw_text;setSelectedId(entry.id);setDay(entry.day);setDraft(entry.raw_text);setSource(entry.source);setKeys(new Set());}
  async function fresh(){setEdited(null);if(!await queue.flushAll()){setNotice('Исправьте ошибку сохранения перед новой записью.');return;}entryIdRef.current=null;draftRef.current='';setSelectedId(null);setDay(localDay());setDraft('');setSource('text');setKeys(new Set());}
  function changeDraft(nextText:string,nextDay=day,nextSource: 'text'|'voice'=source){if(selected?.analysis_json&&entryIdRef.current===selected.id){entryIdRef.current=null;setSelectedId(null);setKeys(new Set());}draftRef.current=nextText;setDraft(nextText);setDay(nextDay);setSource(nextSource);queue.enqueue('journal-draft',async()=>{if(!nextText.trim()&&!entryIdRef.current)return;const entry=entryIdRef.current?await window.nexus.journal.update({id:entryIdRef.current,day:nextDay,text:nextText,source:nextSource}):await window.nexus.journal.save({day:nextDay,text:nextText,source:nextSource});entryIdRef.current=entry.id;setSelectedId(entry.id);await reload();},600);}
  async function analyze(overrideBudget=false){setBusy('analyze');try{if(!await queue.flushAll()){setNotice('Сначала исправьте ошибку сохранения текста.');return;}const entryId=entryIdRef.current;if(!entryId){setNotice('Напишите или начитайте несколько слов о дне.');return;}const result=await window.nexus.journal.analyze(entryId,overrideBudget);await reload();setSelectedId(result.id);setKeys(new Set());setNotice('День разобран. Проверьте предложения перед сохранением.');}catch(e){const msg=errorText(e);if(msg.includes('AI_BUDGET_CONFIRM')){if((await askConfirm('Лимит AI достигнут или стоимость прошлых запросов неизвестна. Разрешить анализ дня?')))await analyze(true);}else setNotice(msg);}finally{setBusy('');}}
  async function transcribe(base64:string,overrideBudget=false){setBusy('transcribe');try{const text=await window.nexus.journal.transcribe({base64,format:'webm',overrideBudget});changeDraft(draftRef.current.trim()?`${draftRef.current.trim()}\n\n${text}`:text,day,'voice');setNotice('Речь распознана. Проверьте текст перед анализом.');}catch(e){const msg=errorText(e);if(msg.includes('AI_BUDGET_CONFIRM')){if((await askConfirm('Лимит AI достигнут или стоимость прошлых запросов неизвестна. Разрешить распознавание записи?')))await transcribe(base64,true);}else setNotice(msg);}finally{setBusy('');}}
  async function startRecording(){if(!settings.data?.aiEnabled){setNotice('Для голосового ввода включите AI в настройках.');return;}if(!settings.data.hasApiKey){try{const profile=await window.nexus.accounts.profile();if(!profile?.active||profile.role!=='guest'||profile.aiMode!=='device'){setNotice('Для голосового ввода нужен личный ключ OpenRouter или ключ, выданный владельцем.');return;}}catch(e){setNotice(errorText(e));return;}}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setNotice('Микрофон недоступен в этой системе.');return;}try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:false});stream.current=s;const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const r=new MediaRecorder(s,{mimeType:mime});chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};r.onstop=()=>{s.getTracks().forEach(t=>t.stop());stream.current=null;setRecording(false);if(timer.current)clearTimeout(timer.current);const blob=new Blob(chunks.current,{type:mime});if(blob.size>0&&blob.size<20_000_000)void asBase64(blob).then(base64=>transcribe(base64)).catch(e=>setNotice(errorText(e)));else setNotice('Запись пуста или слишком велика. Максимум — 20 МБ.');};r.start();recorder.current=r;setRecording(true);timer.current=setTimeout(()=>r.state==='recording'&&r.stop(),180000);}catch{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRecording(false);setNotice('Не удалось включить микрофон. Разрешите доступ в Windows и повторите.');}}
  function stopRecording(){if(recorder.current?.state==='recording')recorder.current.stop();}
  async function apply(){if(!selected||!keys.size)return;setBusy('apply');try{if(!await queue.flushAll())throw new Error('Исправьте предложения перед сохранением.');await window.nexus.journal.apply({id:selected.id,keys:[...keys]});await reload();await Promise.all([health.reload(),finance.reload(),work.reload()]);setKeys(new Set());onApplied();setNotice('Выбранные данные сохранены.');}catch(e){setNotice(errorText(e));}finally{setBusy('');}}
  function changeAnalysis(value:JournalAnalysis){if(!selected)return;const id=selected.id;setEdited({id,value});queue.enqueue('journal-review',async()=>{await window.nexus.journal.editAnalysis({id,analysis:value});await reload();},600);}
  return <Panel eyebrow="ДНЕВНОЙ ЖУРНАЛ" title="Расскажите о дне" className="journal-panel" action={<button className="button small secondary" onClick={()=>void fresh()}>Новая запись</button>}><p className="muted">Запишите события своими словами. AI предложит отметки, операции и изменения статусов. Ничего не попадёт в другие разделы без вашего выбора.</p><div className="journal-grid"><div className="journal-compose"><Field label="Дата"><input type="date" value={day} onChange={e=>changeDraft(draft,e.target.value,source)}/></Field><Field label="Текст дня"><textarea rows={7} value={draft} onChange={e=>changeDraft(e.target.value,day,'text')} placeholder="Например: спал с 23:30 до 7:00, сходил в зал, потратил 650 ₽ на продукты, отправил отклик…"/></Field><div className="button-row"><button className={`button small ${recording?'recording':'secondary'}`} disabled={!!busy} onClick={recording?stopRecording:()=>void startRecording()}>{recording?'■ Остановить запись':'● Начитать'}</button><button className="button small primary" disabled={!!busy||!draft.trim()} onClick={()=>void analyze()}>{busy==='analyze'?'Анализ…':'Разобрать с AI'}</button></div>{draft.trim()&&<SaveIndicator status={saveStatus} onRetry={()=>queue.retry()}/>}{busy==='transcribe'&&<p className="muted">Распознавание речи…</p>}{notice&&<Notice message={notice} onClose={()=>setNotice('')}/>}<div className="journal-history"><h3>Последние 3 записи</h3><p className="muted">Старые тексты удаляются автоматически. Сохранённые отметки и операции остаются.</p>{data?.length?<div className="journal-entry-list">{data.slice(0,3).map(x=><button key={x.id} className={x.id===selectedId?'selected':''} onClick={()=>void select(x)}><strong>{new Date(`${x.day}T12:00:00`).toLocaleDateString('ru-RU')}</strong><span>{x.source==='voice'?'Голос':'Текст'} · {x.raw_text.slice(0,65)}{x.raw_text.length>65?'…':''}</span></button>)}</div>:<p className="muted">Записей пока нет.</p>}</div></div><div className="journal-review">{analysis?<><div className="journal-summary"><div className="eyebrow">СВОДКА AI</div><p>{analysis.summary}</p></div>{analysis.uncertain.length>0&&<div className="help-warning"><strong>Нужно уточнить</strong><ul>{analysis.uncertain.map((u,i)=><li key={i}>{u}</li>)}</ul></div>}<h3>Предложения для сохранения</h3><JournalReview analysis={analysis} accounts={finance.data?.accounts.filter(x=>x.active)??[]} categories={finance.data?.categories.filter(x=>x.active)??[]} habits={health.data?.habits??[]} jobs={work.data?.jobs??[]} selected={keys} applied={applied} onSelect={(key,checked)=>setKeys(prev=>{const next=new Set(prev);if(checked)next.add(key);else next.delete(key);return next;})} onChange={changeAnalysis} busy={!!busy} day={day} transactions={(finance.data?.transactions??[]).map(x=>({day:x.occurred_at.slice(0,10),amount:x.amount_cents,type:x.type,accountId:x.account_id}))}/>
<button className="button primary" disabled={!keys.size||!!busy||(!!analysis&&hasIncompleteSelectedFinance(analysis,keys))} onClick={()=>void apply()}>Сохранить выбранное</button></>:<Empty title="Разбор появится здесь" description="Напишите или начитайте рассказ, затем нажмите «Разобрать с AI»."/>}</div></div></Panel>;
}
