import {RemindersPanel} from '../components/reminders-ui';
import { askConfirm } from '../confirm';
import { AccountsPanel } from './profiles';
import { UpdatePanel } from '../components/updates';
import { useEffect, useRef, useState } from 'react';
import type { Settings } from '../../shared/models';
import { localDay, monthOf } from '../../shared/domain';
import { useAutoSave } from '../autosave';
import { Field, Notice, Panel, SaveIndicator, Stat, errorText, useData } from '../ui';
import { RemoteBackupPanel } from './remote-backup';

export function SettingsPage(){
  const health=useData(window.nexus.health.list);
  const {data,error,loading,reload}=useData(window.nexus.settings.get);
  const usage=useData(window.nexus.settings.usage);
  const finance=useData(window.nexus.finance.list);
  const [form,setForm]=useState<Settings|null>(null),[key,setKey]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const {queue,status:saveStatus}=useAutoSave();
  const [tab,setTab]=useState<'general'|'ai'|'data'>('general');
  const initialized=useRef(false);
  useEffect(()=>{if(data&&!initialized.current){initialized.current=true;setForm(data);}},[data]);
  const change=<K extends keyof Omit<Settings,'hasApiKey'|'dbPath'|'aiManaged'|'aiBudgetCents'>>(name:K,value:Settings[K])=>{setForm(prev=>prev?{...prev,[name]:value}:prev);queue.enqueue(`settings:${name}`,()=>window.nexus.settings.save({[name]:value}),typeof value==='string'?450:0);};
  const changeKey=(value:string)=>{setKey(value);if(value.trim())queue.enqueue('settings:api-key',async()=>{await window.nexus.settings.setApiKey(value);setForm(prev=>prev?{...prev,hasApiKey:true}:prev);setKey(prev=>prev===value?'':prev);},700);};
  async function changeModelMode(custom:boolean){setBusy(true);try{if(!await queue.flushAll())return;await window.nexus.settings.save({aiModelMode:custom?'custom':'preset'});setForm(await window.nexus.settings.get());}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
  async function clearKey(){if(!(await askConfirm('Удалить сохранённый API-ключ OpenRouter?')))return;setBusy(true);try{queue.enqueue('settings:api-key',async()=>{await window.nexus.settings.setApiKey('');setForm(prev=>prev?{...prev,hasApiKey:false}:prev);setKey('');});if(!await queue.flushAll())return;setNotice('Ключ удалён.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
  async function test(){setBusy(true);try{if(!await queue.flushAll())return;await window.nexus.settings.testConnection();setNotice('Подключено.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
  async function exportData(){try{if(!await queue.flushAll())return;const file=await window.nexus.data.export();if(file)setNotice(`Копия сохранена: ${file}`);}catch(e){setNotice(errorText(e));}}
  async function importData(){if(!(await askConfirm('Импорт заменит текущие данные. Перед заменой NEXUS создаст локальную копию базы. Продолжить?')))return;try{if(!await queue.flushAll())return;const imported=await window.nexus.data.import();if(imported){initialized.current=false;await reload();await usage.reload();setNotice('Резервная копия импортирована.');}}catch(e){setNotice(errorText(e));}}
  const month=monthOf(localDay()),monthUsage=usage.data?.filter(u=>u.timestamp.startsWith(month))??[];
  const spent=monthUsage.reduce((s,u)=>s+(u.cost_microusd??0),0),unknown=monthUsage.filter(u=>u.cost_microusd==null&&(u.status==='ok'||!!u.request_id||u.input_tokens!=null)).length;
  return <><div className="page-title"><div><h1>Настройки</h1></div></div>
    <nav className="tabs" aria-label="Разделы настроек">{([['general','Общие'],['ai','ИИ'],['data','Данные и синхронизация']] as const).map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {error&&<div className="error-banner">{error}</div>}{notice&&<Notice message={notice} onClose={()=>setNotice('')}/>}
    {loading&&!form?<div className="loading">Загрузка настроек…</div>:form&&<>
      <form onSubmit={e=>e.preventDefault()} className="settings-form" hidden={tab!=='general'&&tab!=='ai'}>
        <div className="section-view" hidden={tab!=='general'}><UpdatePanel/><RemindersPanel api={window.nexus.reminders} habits={health.data?.habits.filter(x=>x.active)}/></div><div className="settings-columns section-view" hidden={tab!=='general'}><div className="settings-column"><Panel title="Общие"><div className="form-stack"><label className="check-row"><input type="checkbox" checked={form.autostart} onChange={e=>change('autostart',e.target.checked)}/> Запускать при входе в систему</label><Field label="Основная валюта" hint="Смена обозначения не конвертирует сохранённые суммы."><select value={form.currency} onChange={e=>change('currency',e.target.value)}><option value="RUB">Рубль · ₽</option><option value="USD">Доллар · $</option><option value="EUR">Евро · €</option></select></Field><Field label="Первый день недели"><select value={form.firstDayOfWeek} onChange={e=>change('firstDayOfWeek',Number(e.target.value) as 0|1)}><option value={1}>Понедельник</option><option value={0}>Воскресенье</option></select></Field></div></Panel></div><div className="settings-column"><Panel title="Цель поиска"><Field label="Откликов за неделю"><input type="number" min="0" max="1000" value={form.weeklyTarget} onChange={e=>change('weeklyTarget',Number(e.target.value))}/></Field></Panel><Panel title="Основной счёт"><Field label="Счёт для быстрых операций"><select value={form.primaryAccountId??''} onChange={e=>change('primaryAccountId',e.target.value?Number(e.target.value):null)}><option value="">Первый активный счёт</option>{finance.data?.accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field></Panel></div></div>
        <div className="settings-columns section-view" hidden={tab!=='ai'}><Panel title="OpenRouter"><div className="form-stack"><label className="check-row"><input type="checkbox" checked={form.aiEnabled} onChange={e=>change('aiEnabled',e.target.checked)}/> Включить AI-функции</label>{!form.aiManaged&&<label className="check-row"><input type="checkbox" disabled={busy} checked={form.aiModelMode==='custom'} onChange={e=>void changeModelMode(e.target.checked)}/> Выбирать модели вручную</label>}{form.aiModelMode==='custom'&&!form.aiManaged&&<><Field label="Разбор дня и вакансий"><input value={form.cheapModel} onChange={e=>change('cheapModel',e.target.value)} placeholder="provider/model-id"/></Field><Field label="Наставник, анализ и письма"><input value={form.standardModel} onChange={e=>change('standardModel',e.target.value)} placeholder="provider/model-id"/></Field><Field label="Подготовка к интервью"><input value={form.advancedModel} onChange={e=>change('advancedModel',e.target.value)} placeholder="provider/model-id"/></Field><Field label="Распознавание голоса"><input value={form.transcriptionModel} onChange={e=>change('transcriptionModel',e.target.value)} placeholder="provider/transcription-model"/></Field></>}</div></Panel><Panel title="Доступ к OpenRouter"><div className="key-status"><span className={`indicator ${form.hasApiKey?'on':''}`}/>{form.aiManaged?'Персональный ключ':form.hasApiKey?'Ключ сохранён':'Ключ не добавлен'}</div>{!form.aiManaged&&<Field label="Новый API-ключ"><input type="password" autoComplete="off" value={key} onChange={e=>changeKey(e.target.value)} placeholder="sk-or-v1-…"/></Field>}<div className="button-row"><button type="button" className="button secondary small" disabled={(!form.hasApiKey&&!form.aiManaged)||busy} onClick={()=>void test()}>Проверить подключение</button>{!form.aiManaged&&form.hasApiKey&&<button type="button" className="button ghost small" onClick={()=>void clearKey()}>Удалить ключ</button>}</div></Panel>{!form.aiManaged&&<Panel title="Расход AI"><div className="stats-grid"><Stat label="Текущий месяц" value={`$${(spent/1_000_000).toFixed(4)}`}/><Stat label="Запросов" value={monthUsage.length}/></div>{unknown>0&&<p className="help-warning">Для {unknown} запросов OpenRouter не сообщил стоимость. Общий расход может быть выше показанного.</p>}{monthUsage.length>0&&<details className="section-fold"><summary>История запросов</summary><div className="compact-list">{monthUsage.slice(0,12).map(u=><div key={u.id}><span>{u.timestamp.slice(0,16).replace('T',' ')}</span><strong>{u.feature}</strong><span>{u.cost_microusd==null?'Стоимость неизвестна':`$${(u.cost_microusd/1_000_000).toFixed(4)}`}</span></div>)}</div></details>}</Panel>}</div>
        <div className="settings-save"><SaveIndicator status={saveStatus} onRetry={()=>queue.retry()}/></div>
      </form>

      <div className="settings-grid section-view" hidden={tab!=='data'}><Panel title="Резервные копии" className="settings-wide"><div className="button-row"><button className="button secondary small" onClick={()=>void exportData()}>Экспортировать</button><button className="button ghost small" onClick={()=>void importData()}>Импортировать</button></div><div className="divider"/><Field label="Расположение базы"><input readOnly value={form.dbPath}/></Field></Panel><RemoteBackupPanel beforeAction={()=>queue.flushAll()} onRestored={()=>window.location.reload()}/><AccountsPanel/></div>
    </>}</>;
}
