import {WeekComparison} from '../components/insights-ui';
import { askConfirm } from '../confirm';
import { CoachCard } from '../components/life-board';
import { useCallback, useState } from 'react';
import { money } from '../../shared/domain';
import { Empty, Modal, Panel, Progress, Stat, useData } from '../ui';

const date=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
export function WeeklySummaryDialog({currency,onClose}:{currency:string;onClose:()=>void}){
  const life=useData(window.nexus.life.list);
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [period,setPeriod]=useState<'current'|'previous'>('current');
  const loader=useCallback(()=>window.nexus.dashboard.weekly(period),[period]);
  const {data,error,loading}=useData(loader),fmt=(value:number)=>money(value,currency);
  const minutes=(value:number)=>`${Math.floor(value/60)} ч ${value%60} мин`;
  const delta=data?.health.weightStart!=null&&data.health.weightEnd!=null&&data.health.weightMeasurements>1?+(data.health.weightEnd-data.health.weightStart).toFixed(1):null;
  async function review(overrideBudget=false):Promise<void>{if(!data)return;setBusy(true);try{await window.nexus.life.review({kind:'week',start:data.start,end:data.end,overrideBudget});await life.reload();setNotice('');}catch(error){const message=error instanceof Error?error.message:'Не удалось разобрать неделю.';if(message.includes('AI_BUDGET_CONFIRM')&&(await askConfirm('Продолжить разбор недели, несмотря на лимит AI или неизвестную стоимость прошлых запросов?')))await review(true);else setNotice(message);}finally{setBusy(false);}}
  return <Modal title="Итоги недели" onClose={onClose} wide><div className="weekly-summary"><div className="weekly-summary-toolbar"><div className="segmented"><button className={period==='previous'?'active':''} onClick={()=>setPeriod('previous')}>Прошлая неделя</button><button className={period==='current'?'active':''} onClick={()=>setPeriod('current')}>Текущая неделя</button></div>{data&&<span>{date(data.start)} — {date(data.end)}</span>}</div>{error&&<p className="error-banner">{error}</p>}{loading?<p className="loading">Собираю итоги…</p>:data&&<><div className="stats-grid weekly-summary-stats"><Stat label="Расходы" value={fmt(data.finance.expense)}/><Stat label="Доходы" value={fmt(data.finance.income)}/><Stat label="Изменение веса" value={delta===null?'—':`${delta>0?'+':''}${delta} кг`} sub={`${data.health.weightMeasurements} измерений за неделю`}/><Stat label="Средний сон" value={data.health.sleepAverage===null?'—':minutes(data.health.sleepAverage)} sub={`${data.health.sleepDays} дней с записью`}/></div><WeekComparison start={data.start} end={data.end} currency={currency}/><div className="content-grid"><Panel title="Привычки" eyebrow="РЕГУЛЯРНОСТЬ">{data.health.habits.length?data.health.habits.map(h=><div className="weekly-habit-row" key={h.id}><div><strong>{h.name}</strong><b>{h.completed} / {h.expected}</b></div><Progress value={h.completed} max={h.expected}/><small>{h.period==='weekly'?'Недельная привычка · ':'Ежедневная привычка · '}{Math.max(0,h.observed-h.completed)} не выполнено</small></div>):<Empty title="Нет активных привычек"/>}</Panel><div className="weekly-summary-side"><Panel title="Основные расходы" eyebrow="ЗА НЕДЕЛЮ">{data.finance.categories.length?<div className="compact-list">{data.finance.categories.map((c,i)=><div key={i}><span>{c.name}</span><strong>{fmt(c.amount_cents)}</strong></div>)}</div>:<p className="muted">Расходов за неделю нет.</p>}</Panel><Panel title="Инвестиции" eyebrow="БЕЗ ПОПОЛНЕНИЙ И ВЫВОДОВ">{data.investments.length?<div className="compact-list">{data.investments.map((i,index)=><div key={index}><span>{i.name}<small>{i.measurements} оценок за неделю</small></span><strong>{i.profit===null?'Нет оценок':`${i.profit>0?'+':''}${fmt(i.profit)}`}</strong></div>)}</div>:<p className="muted">Портфелей пока нет.</p>}</Panel></div></div><div className="weekly-coach-action"><button className="button primary" disabled={busy} onClick={()=>void review()}>{busy?'Разбираю неделю…':'Разбор недели с ИИ'}</button><span className="muted">Что получилось, где просели и следующие шаги.</span></div>{notice&&<p className="error-banner">{notice}</p>}<CoachCard saved={life.data?.reviews.find(x=>x.kind==='week'&&x.start===data.start&&x.end===data.end)}/></>}</div></Modal>;
}
